### ISSUE TITLE
Add ability to count flags

### ISSUE THREAD

**Issue by vincentbernat** [pcapriotti/optparse-applicative#107]
Hey!

For some flags, being able to repeat a flag can be useful. For example if `-v` increases verbosity, using `-vvv` would increase verbosity a lot. This could be done by using a counter to store the number of `-v` or to use the next possible value of an enum:

``` haskell
data Verbosity = Normal | Verbose | Debug | All
```

**Comment by HuwCampbell** [comment]
Just a heads up that as of 0.12 (releasing soon) `-vvv` will work in the top style as well, as we allow short flags together now.
