### ISSUE TITLE
Subcommand aliases

### ISSUE THREAD

**Issue by magthe** [pcapriotti/optparse-applicative#113]
It would be really cool if it were possible to provide aliases for subcommands, e.g. through a variant of `command` that takes a list of `String`.

**Comment by d12frosted** [comment]
The same here

**Comment by d12frosted** [comment]
Hey, currently I have a simple workaround:

```haskell
cmd' :: String -> [String] -> Parser a -> String -> Mod CommandFields a
cmd' s [] p d = command s (info p (progDesc d))
cmd' s (a:as) p d = cmd' s as p d <> command a (info p (progDesc $ "alias for '" ++ s ++ "'"))
```

Minor draw back:

```haskell
cmd' "two" ["2", "2.0"] (pure 2) "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean id lectus sed dui condimentum dignissim tempus eget magna. Integer orci tortor, lobortis sed elit ac, pellentesque varius felis. In tristique felis diam, ac lobortis sem blandit in. Aenean porttitor enim quis eros interdum viverra. Vivamus ullamcorper dictum lectus, a convallis tortor aliquet a. Aenean vel lorem tortor. Nulla id urna nisl."
```

Gives us 

```
  two                      Lorem ipsum dolor sit amet, consectetur adipiscing
                           elit. Aenean id lectus sed dui condimentum dignissim
                           tempus eget magna. Integer orci tortor, lobortis sed
                           elit ac, pellentesque varius felis. In tristique
                           felis diam, ac lobortis sem blandit in. Aenean
                           porttitor enim quis eros interdum viverra. Vivamus
                           ullamcorper dictum lectus, a convallis tortor aliquet
                           a. Aenean vel lorem tortor. Nulla id urna nisl.
  2.0                      alias for 'two'
  2                        alias for 'two'
```

(aliases are reverted)

**Comment by d12frosted** [comment]
Or you can checkout 31e208d2bbe269e45ae71e51f51a3004dafd46df

**Comment by magthe** [comment]
It's taken me a *long* time to get around to this... any particular reason why 31e208d never was merged?

**Comment by HuwCampbell** [comment]
Hi, sorry for not responding on this one earlier.
I mentioned a few of my concerns about something similar in PR #122.
Biggest one is that I don't think hidden should exist on `ParserInfo`, as it's the top level datatype, and hidden makes no sense for a programs main parser.
Second reason is that we support having multiple subparsers, hidden subparsers, and alternative, so one can implement this behaviour pretty easily with something like
```haskell
subparser (command "main" cmdpinfo) <|> subparser (command "alias" cmdpinfo  <> internal)
```

**Comment by HuwCampbell** [comment]
In #197 (the examples) I show a potential way to implement this (only the group name part can not be done at the moment).

**Comment by HuwCampbell** [comment]
Is the French commands example in the manual acceptable? I would like to close this off.

**Comment by magthe** [comment]
Yes, looks perfect! Closing it!
