### ISSUE TITLE
HasCompleter instance for CommandFields

### ISSUE THREAD

**Issue by mightybyte** [pcapriotti/optparse-applicative#115]
Any chance we could get this instance?  It would be nice to be able to complete commands.  Also, is it possible to have different completers for different commands?  For instance, if cabal was written using this library you could have one dynamic set of completions after "cabal sandbox" and another set after "cabal sandbox hc-pkg".

**Comment by HuwCampbell** [comment]
This is already the case without the proposed change.
When bash completion runs it will enter the contexts of any subparser commands and allow completion within said contexts.
Actual commands are completed with their name, as this is the only thing that makes sense.
