### ISSUE TITLE
auto ambiguity

### ISSUE THREAD

**Issue by MichaelXavier** [pcapriotti/optparse-applicative#130]
Hi,

I've got a program that has to parse version numbers from the command line a-la `Data.Version`. Currently I'm using the `auto` function but it doesn't seem to handle ambiguous parses well. For instance, if you parse "2.3" with ReadS, it produces `[(2,".1"),(2.1,"")]`. The pattern match in the code expects exactly 1 parse with the input fully consumed. I propose it would be better to filter the parses and select if there's 1 and only 1 case that fully consumes the input. If you wanted to be more lax, it could select the first one matching this criteria or fail otherwise.

I'm happy to do the work and submit a PR on this, but I wanted to make sure it would be accepted and which route you'd prefer. In the mean time I can of course use my own version of auto.

**Comment by HuwCampbell** [comment]
Can you show me your problematic parser?

**Comment by MichaelXavier** [comment]
It was a while since I had this issue but here's what I came up with: https://gist.github.com/MichaelXavier/42c0d441be65ca49e6c4

All the newtype machinery is becase Version supplies a non-typeclassed ReadS for parsing simple version numbers, e.g. "2.3".  You'll note that unambiguous parses "2" produces [(Version 2, "")], so it doesn't fail the pattern match. "2.3" produces [(Version 2, ".3"), (Version 2 3, "")], fails the pattern match and thus the flag fails. I'm arguing that if this function scanned through and found exactly one parse that consumed all the input (Version 2 3, ""), that would be better.

**Comment by HuwCampbell** [comment]
I'll be honest, I don't think it's a good idea. It doesn't seem precise.
That said, there are already things that one can do to make readers better. For example:
```
import qualified Data.Attoparsec.Text as A
-- | Turn an attoparsec parser into a ReadM
pOption :: A.Parser a -> ReadM a
pOption p = either readerError pure =<< (ReadM . ReaderT $ pure . A.parseOnly p . T.pack)
```

**Comment by MichaelXavier** [comment]
That's fair. I think I'll prefer this strategy in the future.
