### ISSUE TITLE
selectReader

### ISSUE THREAD

**Issue by phadej** [pcapriotti/optparse-applicative#131]
I find this useful when specifying enumerable options:

```hs
selectReader :: [(String, a)] -> ReadM a
selectReader opts = readerAsk >>= lookup'
  where lookup' s = maybe (readerError err) return $ lookup s opts
          where err = "Unknown option: " ++ s  ++ ", available: " ++ L.intercalate ", " (P.map fst opts)
```

The usage is as simple as
```hs
fooReader :: ReadM Foo
fooReader = selectReader [ ("foo", Foo)
                         , ("bar", Bar)
                         , ("quux", Quux)
                         ]
```

IMHO: better than using `eitherReader`. Or is there some option I miss from documentation?

Would you like a PR with this?

**Comment by pcapriotti** [comment]
I think simple and short utility functions like these belong to user code. It's really hard to write them in a way that makes everybody happy, anyway.
