### ISSUE TITLE
Optional option args?

### ISSUE THREAD

**Issue by fosskers** [pcapriotti/optparse-applicative#137]
Problem: A program has an option, say `-f` which can either take an argument or not.

(Albeit hacky) Solution:

```haskell
data Flag = F (Maybe String)

flags :: Parser Flag
flags = F <$>
         (flag' Nothing (long "foo" <> short 'f' <> help "Helpful message.")
         *> optional (argument str (metavar "ARG")))
```

PROs:
- We get the behaviour we expect. `prog -f` and `prog -f arg` both parse.
- The "short" help renders as we expect: `Usage: prog (-f|--foo) [ARG])`

CONs:
- While `--foo arg` works, `--foo=arg` does not.
- While `-f arg` works, `-farg` does not.

Is there some canonical solution to this that I'm just missing? Or is my suggestion here the only way to achieve this, despite the cons?

**Comment by pcapriotti** [comment]
See #67.

**Comment by fosskers** [comment]
For now home-spun solution seem to be it then eh?
