### ISSUE TITLE
Showing global options in command parsers

### ISSUE THREAD

**Issue by chrisdone** [pcapriotti/optparse-applicative#138]
Is it possible to have e.g. `foo --help` produce

```
Usage: <interactive> [--version] [--help]  [--verbose ARG] COMMAND

Available options:
  --version                Show version
  --help                   Show this help text
  --verbose ARG            Set verbosity

Available commands:
  dothing                    do the thing
```

and then `foo dothing --help` produce

```
Usage: <interactive> [--verbose ARG] dothing
  do the thing
```

like that? So that `--verbose` is still listed because it's a global option but applies to `dothing` too?

**Comment by edsko** [comment]
+1 :)

**Comment by bollmann** [comment]
+1

**Comment by HuwCampbell** [comment]
I've made some changes to how contexts are carried through, so this should be easier now.

**Comment by nomeata** [comment]
+1

**Comment by nomeata** [comment]
I am very interested in having a fix for this. Does anyone maybe have a somewhat doable workaround for this?

**Comment by borsboom** [comment]
There is a workaround, although it's a bit of work.  Basically you have to add the global options parser both in the outer parser and to every subcommand parser, and then you combine the "outer" global options with the "inner" global options (having the inner options take precedence).  You also have to make sure you set `(prefs noBacktrack)` for this case to avoid confusing behaviour.  We do this in `stack`, and the [Options.Applicative.Complicated](https://github.com/commercialhaskell/stack/blob/master/src/Options/Applicative/Complicated.hs) module has most of the guts of that.

**Comment by nomeata** [comment]
Hmm. Sounds as if its almost easier to only have local options then.

**Comment by bitc** [comment]
Why was this issue closed? There still doesn't seem to be a way to do this (apart from the complicated workaround of @borsboom)
