### ISSUE TITLE
Completion with commands

### ISSUE THREAD

**Issue by phadej** [pcapriotti/optparse-applicative#140]
I try to use competion functionality, but seems it's broken when there are subcommands. Or did I constructed my parser wrong?

## Steps to reproduce

```haskell
#!/usr/bin/env stack
-- stack runghc --package optparse-applicative

import Options.Applicative
import Options.Applicative.BashCompletion -- bashCompletionQuery is not exported though
import Options.Applicative.Builder
import Options.Applicative.Common
import Options.Applicative.Internal
import Options.Applicative.Types

import Data.List (isPrefixOf)
import Data.Maybe (fromMaybe, listToMaybe)

-- Copy from Options.Applicative.BashCompletion
bashCompletionQuery :: ParserInfo a -> ParserPrefs -> [String] -> Int -> String -> IO [String]
bashCompletionQuery pinfo pprefs ws i _ = case runCompletion compl pprefs of
  Just (Left (SomeParser p)) -> list_options p
  Just (Right c)             -> run_completer c
  _                          -> return []
  where
    list_options =
        fmap concat
      . sequence
      . mapParser (const opt_completions)

    opt_completions opt = case (propVisibility $ optProps opt, optMain opt) of
      (Hidden, _)           -> return []
      (Internal, _)         -> return []
      (_, OptReader ns _ _) -> return $ show_names ns
      (_, FlagReader ns _)  -> return $ show_names ns
      (_, ArgReader rdr)    -> run_completer (crCompleter rdr)
      (_, CmdReader ns _)   -> return $ filter_names ns

    show_name :: OptName -> String
    show_name (OptShort c) = '-':[c]
    show_name (OptLong name) = "--" ++ name

    show_names :: [OptName] -> [String]
    show_names = filter_names . map show_name

    filter_names :: [String] -> [String]
    filter_names = filter is_completion

    run_completer :: Completer -> IO [String]
    run_completer c = runCompleter c (fromMaybe "" (listToMaybe ws''))

    (ws', ws'') = splitAt i ws

    is_completion :: String -> Bool
    is_completion =
      case ws'' of
        w:_ -> isPrefixOf w
        _ -> const True

    compl = runParserInfo pinfo (drop 1 ws')
--

data EslintOpts = EslintOpts
  { eoConfig :: FilePath
  , eoFiles :: [FilePath]
  }
  deriving (Eq, Show)

data Command = EslintCommand EslintOpts
  deriving (Eq, Show)

fileArgument :: Parser FilePath
fileArgument = strArgument (metavar "FILE")

eslintOptsParser :: Parser EslintOpts
eslintOptsParser = EslintOpts <$> strOption (short 'c' <> long "config" <> metavar "CONFIG" <> value ".eslintrc")
                              <*> many fileArgument

commandParser :: Parser Command
commandParser = subparser $ command "eslint" (info (EslintCommand <$> eslintOptsParser) (progDesc "Lint javascript sources"))

test1 = bashCompletionQuery (info (helper <*> commandParser) idm) (prefs idm) ["esli"] 0
test2 = bashCompletionQuery (info (helper <*> commandParser) idm) (prefs idm) ["esli", "--confi"] 0
test3 = bashCompletionQuery (info (helper <*> commandParser) idm) (prefs idm) ["eslint", "--confi"] 1
test4 = bashCompletionQuery (info (helper <*> commandParser) idm) (prefs idm) ["eslint", "--he"] 1
test5 = bashCompletionQuery (info (helper <*> commandParser) idm) (prefs idm) ["eslint"] 1

main :: IO ()
main = do
  test1 "" >>= print
  test2 "" >>= print
  test3 "" >>= print
  test4 "" >>= print
  test5 "" >>= print

```

## Actual output

```haskell
["eslint"]
["eslint"]
[]
[]
["eslint"]
```

## Expected output

```haskell
["eslint"]
["eslint"]
["-c", "--config"]
["--help"]
["-c","--config"]
```

**Comment by HuwCampbell** [comment]
You're trying to complete two items at the same time, which isn't the point as people type one word at a time. Working through the examples.

1: You're completing `eslint`. Good
2: You're completing `eslint`. Yep, that's fine.
3: You're completing `--confi`. You're not inside eslint, because it's not typed correctly, so --config doesn't exist. But this situation wouldn't ever occur if you were using completion because you'd type esli<tab>, then get `eslint` then start typing --config, when it would exist and would complete.
4: Help is on the top level, so are you because `eslint` hasn't been entered. Again this example makes no sense for actual usage when you would have completed esli with <tab>.
5: You're on the top level still as esli is hasn't been completed, and you're tabbing to see all top level options, which are help and eslint. This again doesn't make sense for actual usage, where you would have pressed <tab> on esli and it would have competed.

**Comment by phadej** [comment]
@HuwCampbell I updated the description with (stack) runnable example, fixed also `esli` to `eslint`. It still doesn't work.

**Comment by HuwCampbell** [comment]
Completion parser takes an extra item at the start which is the name of the executable. That's why there's a drop 1 in there.
If you write the parser as an executable, source the file, and run it with execparser, it should work.

**Comment by HuwCampbell** [comment]
I'm satisfied that there's no bug here. Reopen if needed.

**Comment by phadej** [comment]
I don't understand "drop 1". It doesn't affect anything. In subcommand example options (`-c` and `--config`) aren't completed. For example without subcommand:

```hs
test6 = bashCompletionQuery (info (helper <*> eslintOptsParser) idm) (prefs idm) [""] 0
test7 = bashCompletionQuery (info (helper <*> eslintOptsParser) idm) (prefs idm) ["--conf"] 0
```

Actual and expected outputs are:
```
["--config","-c"]
["--config"]
```

---

I cannot find any test case about subcommands + bash completion, or bash completion itself.

**Comment by phadej** [comment]
Also I cannot reopen this issue.

**Comment by HuwCampbell** [comment]
`["programname", "esli"] 1`
`["programname", "--conf"] 1`

**Comment by HuwCampbell** [comment]
Sorry, I don't mean to be dismissive if you felt that way. I compiled your program, loaded the bash completion script and found that it worked, I then spent a few hours figuring out what the misunderstanding was.
You were calling the internal API incorrectly, the bash completion script also includes the program name as the first argument.
