### ISSUE TITLE
multi-word filename completion is broken

### ISSUE THREAD

**Issue by joeyh** [pcapriotti/optparse-applicative#146]
The bash completion support in optparse-applicative is really great. I found a problem with it though. When I used action "file" to have an argument completed using filenames, it seemed to work ok -- until I tried completing a filename that contained spaces. For example, if there's a file "foo bar", and I tab complete "foo", the result is that bash offers two completion choices, foo and bar.

So, there seems to be some confusion between the output of optparse-applicative, and what bash expects to get. The output is multiple lines, one per completion (eg "foo bar\nfoo baz\n" for multi-word filenames). I think this is not being fed into COMPREPLY
properly, and is instead tokenized into words.

I wonder if it would be better to use complete -A, rather than complete -F, since -A makes bash expect the completion function to output each completion on its own line.

**Comment by HuwCampbell** [comment]
Looks like this can be fixed by editing the completion script to have
```bash
local cmdline
local IFS=$'\n'
```

**Comment by HuwCampbell** [comment]
Did you manage to test that suggestion and was it sufficient for you?

**Comment by joeyh** [comment]
Yes, your suggested fix does work.

**Comment by HuwCampbell** [comment]
#161

**Comment by HuwCampbell** [comment]
I believe #161 has fixed this.
