### ISSUE TITLE
relax bounds for process 1.3

### ISSUE THREAD

**Issue by joeyh** [pcapriotti/optparse-applicative#153]
process-1.3 only added some new record fields, so optparse-applicative will build with it. Please relax the bounds in the cabal file.

**Comment by HuwCampbell** [comment]
I've done this already. #150

**Comment by joeyh** [comment]
Huw Campbell wrote:
> I've done this already. #150

Sorry about the duplicate bug. I guess I wouldn't have filed it if the
fix was released to hackage; as it is, I'm still blocked installing the
new process version.

-- 
see shy jo

**Comment by HuwCampbell** [comment]
Yep, I'll be preparing a release soon.
