### ISSUE TITLE
Monadic parsing?

### ISSUE THREAD

**Issue by adnelson** [pcapriotti/optparse-applicative#154]
I just started using this library and it's pretty awesome. However, I would love to be able to use the parser as a Monad; this would make it a lot easier to make more complicated decisions about how to respond to input (e.g. "attempt to parse this option, and if they haven't supplied it then do this"; or "read this environment variable as the default, and override it with this option if it's supplied" etc).

I see that there's a `ParserM` type which has a monad instance. Why does the regular `Parser` type not have an instance, and how hard would it be to modify it to add it?

**Comment by HuwCampbell** [comment]
Yeah no (it's called optparse-applicative for a reason). Briefly looking at Control.Applicative you'll see
```
If f is also a Monad, it should satisfy
    pure = return
    (<*>) = ap
```
This would totally break optparse-applicative.

Some of the great things about optparse-applicative are that we can traverse the built up syntax tree in advance and produce good error messages and usage texts, we can specify flags out of order...

See #118 for a way to do environment variables. You're other example is a bit vague, but using `<|>` or `subparser` is almost certainly sufficient to do what you want.
