### ISSUE TITLE
export HasCompleter from non-internal module

### ISSUE THREAD

**Issue by joeyh** [pcapriotti/optparse-applicative#155]
HasCompleter is in the .Internal module. That makes code like this potentially break when internals change:

  completeRemotes :: HasCompleter f => Mod f 
  completeRemotes = completer $ mkCompleter ..

  completeBackends :: HasCompleter f => Mod f a
  completeBackends = completeWith (map Backend.name Backend.list)

Since I want these to work for both OptionFields and ArgumentFields, I can't specialize the f, and so need the HasCompletor. Of course, I could instead define these as:

  completeRemotes :: Completer
  completeRemotes = mkCompleter ..

  completeBackends :: [String]
  completeBackends = map Backend.name Backend.list

But the different types and different ways to use these two values seem less simple and composable than the first version. Especially because completeBackends's type doesn't tell what it's for at all.

So, could you please have one of the non-Internal modules export HasCompleter?

**Comment by HuwCampbell** [comment]
optparse doesn't actually have any internal modules, it's just naming. So there's no more risk than any other part of the API.

**Comment by HuwCampbell** [comment]
Done
