### ISSUE TITLE
`argument` does not backtrack, but `option` does backtrack

### ISSUE THREAD

**Issue by Gabriel439** [pcapriotti/optparse-applicative#166]
There seems to be inconsistent backtracking behavior between `argument`s and `option`s.  Here's a minimal reproducing example of the inconsistency:

```haskell
import Options.Applicative

rdr :: String -> ReadM ()
rdr name = do
    s <- str
    if name == s
    then return ()
    else readerAbort ShowHelpText

match :: String -> Parser ()
match name = argument (rdr name) mempty

match' :: String -> Parser ()
match' name = option (rdr name) (long name)

main = do
    execParser (info (helper <*> (match "foo" <|> match "bar")) mempty)
    putStrLn "Success"
```

The above program succeeds when the first argument is `foo`, but not `bar`:

```bash
$ ./example foo
Success
$ ./example bar
Usage: example.hs

Available options:
  -h,--help                Show this help text
```

However, if you replace `match` with `match'`, then both of the `option`-based alternatives succeed:

```bash
$ ./example --foo foo
Success
$ ./example --bar bar
Success
```

**Comment by HuwCampbell** [comment]
Hi Gabriel,
We haven't met yet, but hopefully next big conference. I'm not sure if this is a bug, the linked report says they're trying to simulate subparsers with arguments, but we have support subparsers already... can they just use those? If they can't that's probably the bigger issue I would like to tackle.

Onto the report: I think what's going on here is actually pretty consistent. Imagine, perchance, we have an option `count`, which takes an int:
`let c = option auto (long "count" <> short 'c') :: Parser Int`
if someone uses -c on the command line and doesn't but in an integer, we don't want to take the alternative path, we should really fail hard. That is:
`c <|> pure 1` should not succeed with `1` if we type `-c typo`. It should give us a parse error saying it couldn't parse this.

I propose that this should be the same for arguments. `(argument auto mempty :: Parser Int) <|> pure 2` should not succeed and give a good result with command line args "cake".

With the example you gave, it will probably all fall apart with command line arguments
`$ ./example --foo bar` or `$ ./example --bar foo`.

I might be missing something, feel free to set me straight if I have missed the point.

**Comment by Gabriel439** [comment]
Okay, I think I understand now and that makes sense to me.  If I may restate your explanation in my own words to ensure that I understand things correctly, there are essentially two things that `optparse-applicative` is parsing:

* The "skeleton" of the command line (i.e. the number of arguments, and the option flags)
* The "payload" of the command line (i.e. the part that the parser extracts and returns)

The parser backtracks when parsing the "skeleton", but not when parsing the "payload".  The purpose of the `subcommand` functionality is to mark certain positional arguments as belonging to the skeleton and not the payload so that the parser knows to backtrack if they fail to parse.

So I think I agree with you then that the idiomatic solution is to reuse `optparse-applicative`'s `subcommand` support in `turtle`'s option parsing API.
