### ISSUE TITLE
Need to relax upper bound on process

### ISSUE THREAD

**Issue by svenpanne** [pcapriotti/optparse-applicative#168]
optparse-applicative currently doesn't work with GHC HEAD because the upper bound on `process` is too tight (1.4 should be allowed, too), see e.g. https://travis-ci.org/svenpanne/HSuperBible7/jobs/93786700.

Either releasing a new version on Hackage or directly relaxing the version bound via Hackage would be nice.

**Comment by HuwCampbell** [comment]
#170

**Comment by HuwCampbell** [comment]
Merged. Thanks.

**Comment by svenpanne** [comment]
Is there an ETA for a new release on Hackage with that fix? Even relaxing the bounds for the current release via the Hackage maintainer interface would be nice.
