### ISSUE TITLE
Bash argument completion after `--`

### ISSUE THREAD

**Issue by hjwylde** [pcapriotti/optparse-applicative#172]
Just been fiddling around with the bash completion side of optparse-applicative and it looks to me like after typing out `binary -- <TAB>` it still tries to auto-complete any options that `binary` may have, rather than just the arguments that `--` implies follow.

**Comment by HuwCampbell** [comment]
Should be fixed after #214 the reason being, the options should no longer be considered at all, so only the arg's completion will be invoked.
