### ISSUE TITLE
Need to relax upper bound on transformers package

### ISSUE THREAD

**Issue by svenpanne** [pcapriotti/optparse-applicative#174]
With the current GHC HEAD (i.e. the upcoming 8.0), using optparse-applicative fails because the transformers package is now at 0.5.0.0, see e.g. https://travis-ci.org/svenpanne/HSuperBible7/jobs/98138697

I think transformers-compat will need a bump, too, but AFAICT there is currently no released version which would work with transformers-0.5.0.0, I'll open a ticket there, too.

**Comment by HuwCampbell** [comment]
Looks like work on transformers-compat is underway.

**Comment by HuwCampbell** [comment]
Merged in #181

**Comment by HuwCampbell** [comment]
Done
