### ISSUE TITLE
List detailed subparser documentation with `--help`

### ISSUE THREAD

**Issue by nomeata** [pcapriotti/optparse-applicative#175]
Hi,

the output would probably get rather large, but I still would like my users to enter `foo --help` and learn not just about global options and a concise list of subcommands, but also a full description of each command, including their options, so that they do not have to run `foo subcommand --help` for each of them.

Thanks,
Joachim

**Comment by HuwCampbell** [comment]
This seems like a reasonable request, but it's not trivial.
Given how subparsers are implemented, the top parser knows nothing about it's children; and they of their parent. It's tightly bound to #142 in that respect. So it might require changing the way context is dragged up and down again.

**Comment by chreekat** [comment]
fwiw, I'd like a middle ground, where `foo --help` looks like:

    sdb.hs: a wrapper to set up environment variables and run various
    commands for your local postgres database for Snowdrift.coop
    development.

    Usage:

        sdb.hs ACTION [ARGS]

    Where ACTION may be one of:

        init              initialize the database cluster and databases
        start             start the cluster
        stop              stop  the cluster
        clean             "rm -rf" the whole cluster
        reset             re-init the cluster and databases
        export            create data dumps with pg_dump

        # Expert commands:
        pg_ctl            run Postgres' pg_ctl(1) utility
        psql DATABASE     connect to DATABASE with psql

**Comment by chreekat** [comment]
ok, that's more of a fork in the road than a middle ground, but ... :)

**Comment by HuwCampbell** [comment]
So @chreekat your think should be possible after #197

**Comment by HuwCampbell** [comment]
Addressed in #385 

Feel free to follow up if you think something isn't covered.
