### ISSUE TITLE
hsubparser needs documentation

### ISSUE THREAD

**Issue by nomeata** [pcapriotti/optparse-applicative#177]
I stumbled over this function in the code and found #71 and #55, but it would be nice if `hsubparser` would receive some documentation, and maybe a pointer from the docs of `subparser`.

**Comment by HuwCampbell** [comment]
Thanks for the report
#178

**Comment by nomeata** [comment]
Thanks. I take it that there is no difference between `hsubparser` and `subparser` with manually adding `helper` to each subcommand, then?

**Comment by HuwCampbell** [comment]
That's right.
