### ISSUE TITLE
Include default value in help

### ISSUE THREAD

**Issue by mietek** [pcapriotti/optparse-applicative#179]
It would be nice to see the default value of an option automatically included in the option’s description.

**Comment by HuwCampbell** [comment]
There's two functions, `showDefault` and `showDefaultWith` which allow this.

**Comment by mietek** [comment]
Yes, however, I did mean “automatically”. Currently, the user of this library has to remember to include one of these functions as a modifier; I think it would be nice if this wasn’t necessary.

Is there a situation in which a default value of an option needs to remain secret?

**Comment by HuwCampbell** [comment]
The issue is that doing so would require having `Show` instances for any default, which would be overly restrictive.
