### ISSUE TITLE
Missing support for GHC 8

### ISSUE THREAD

**Issue by asr** [pcapriotti/optparse-applicative#183]
I couldn't install the library using GHC 8.0.1 RC1.

In relation to the dependency on transformers-compat, see https://github.com/ekmett/transformers-compat/issues/11#issuecomment-171136257.

**Comment by hvr** [comment]
fwiw, `transfomers-compat-0.5.*` has been released...

**Comment by HuwCampbell** [comment]
This should be fixed tomorrow.

**Comment by HuwCampbell** [comment]
I've just released 0.12.1 with these updates. Please let me know if there's any issues

**Comment by asr** [comment]
Thanks!
