### ISSUE TITLE
Render usage information with custom error from outside the parser definition

### ISSUE THREAD

**Issue by nd2s** [pcapriotti/optparse-applicative#188]
I have some parser:

    options :: Parser (IO ())
    options = subparser $
        command "serve" (info (handleServe <$> (SrvOpts
                <$> strOption [...]

And need to be able to render usage information based on `options` with a custom error message from outside `options`.

**Comment by HuwCampbell** [comment]
I'm not sure exactly what you mean, a little more context might be useful.
Trying to help though, one can look at `parserFailure` to see how we build up the `ParserHelp` record.
You could build your own record using the help components, or run `parserFailure` and it's reader then replacing the part of the record you wish to be different.

**Comment by nd2s** [comment]
I hope I can make my intentions clearer: I'm doing "complex" validation checks on the parameters (example: if value of *-a* is *X* then there has to be at least one *-b* with value of format *Y*). I'd like to be able to call something like `printErrWithUsage options "-a X set but -b with Y missing"` from inside `handleServe`.

Can I do that with `parserFailure`? I'm afraid I don't fully understand how that works.

**Comment by HuwCampbell** [comment]
You can call `parserFailure` with the `ParseError` as an `ErrorMsg "Your message here"`.
Then call `renderFailure` or `handleParseResult` with its result. This should do what you want and fit in pretty seamlessly.

On a somewhat related note, and not knowing your program or use case, my intuition is that most command line parsers can be written in a fully applicative style without requiring these sort of extra checks. So I would might hazard to suggest thinking about a more precise parser definition as well (it's not always possible, but it very often is).

**Comment by nd2s** [comment]
Thanks for your help.

I moved most of the checks into the `option` definitions, as you said. Seems to work nicely, but I'd need to do some final checks on my `SrvOpts` with all values present before passing it to `handleServe`. Something like this:

    command "serve" (info (handleServe <$> (validationThatCanFail . SrvOpts <$>`

Is there a way to raise an error from the `Parser` context?

And there seems to be a problem with `parserFailure`. It takes a `[Context]` but that's only available via the *Internal* module (and I don't see a way of extracting a `Context`, nor an explanation what that actually is).

**Comment by HuwCampbell** [comment]
If I understand your question correctly, no, that would require bind, which we intentionally do not provide as it makes the parse tree untraversable.

That's a good point regarding `Context` being internal. In the next release I might move it to `Types`.

They describe subparser contexts so that if one says `git add ...` they see the help text for `add` rather than the top level parser (The constructor takes the subparser name and it's ParserInfo). For a top level definition, the empty list will be fine.

**Comment by nd2s** [comment]
Ah, thanks that helped, everything working fine. I'm importing `Internal` now. Will fix when new version is released.
