### ISSUE TITLE
How to handle situation when no command is passed

### ISSUE THREAD

**Issue by Heather** [pcapriotti/optparse-applicative#190]
I'm using arrows, here is code:

``` haskell
parser = runA $ proc () → do
  opts ← asA commonOpts ⤙ ()
  cmds ← (asA . hsubparser)
      (  command "foo"      (info foo (progDesc "..."))
      <> command "bar"      (info (pure Bar)  (progDesc "..."))
      ) ⤙ ()
  A _version ⋙ A helper ⤙ Args opts cmds

run ∷ Args → IO ()
run (Args _ Bar)  = bar
...

main ∷ IO ()
main = execParser opts ≫= run
  where opts = info parser (...)
```

now I want to handle situation when no arguments is passed but I don't fully understand how can I do it there?

**Comment by HuwCampbell** [comment]
You should use the alternative instance of the Parser and have a pure command for when the subcommand parse fails.

**Comment by Heather** [comment]
@HuwCampbell may you provide example, it's complicated for me to see full picture

**Comment by HuwCampbell** [comment]
Sure, I might not use arrows though. Something along the lines of:
```haskell
let parser = Args <$> commonOpts <*> (hsubparser (command "bar" (info (pure Bar)  (progDesc "..."))) <|> pure Baz)
```
should do the trick. If the subparser fails (is given no input or doesn't match) then the other side of the alternative will run.

Usually this wouldn't be desirable, for most command line parsing a better solution is to fail with the help text turned on (similar to what git does).

**Comment by Heather** [comment]
@HuwCampbell thanks! how can I add _help and _version to it?

**Comment by HuwCampbell** [comment]
People often use another alternative for version commands, just a `flag'` as an alternative to `Parser Args` would do.
For help, see how `hsubparser` is implemented and do the same at the top level.

**Comment by Heather** [comment]
@HuwCampbell I've checked `hsubparser` implementation but it's not very descriptive for me so far

I need more tips please

**Comment by HuwCampbell** [comment]
Use the helper function from `Options.Applicative.Extra`.
A common pattern is to do so while creating ParserInfo data, e.g., `info (parser <**> helper) idm`

**Comment by Heather** [comment]
@HuwCampbell  okay... maybe it's better to add ability to handle default action in arrow syntax

**Comment by Heather** [comment]
thanks, solved
