### ISSUE TITLE
Parser.some is not just an optimization of Alternative.some

### ISSUE THREAD

**Issue by amigalemming** [pcapriotti/optparse-applicative#200]
I want to have a `some` that returns a non-empty list. I tried the following:
~~~~
some :: OP.Parser a -> OP.Parser (NonEmpty [] a)
some p = OP.liftA2 NonEmpty.cons p (OP.many p)
~~~~
Unfortunately this parser makes the help option show the metavar of `p` twice. That is, if `p` has name `SRC` it shows `SRC [SRC]`. Copying the internal definition of `some` I tried:
~~~~
some :: OP.Parser a -> OP.Parser (NonEmpty [] a)
some p = OPTyp.fromM $ OP.liftA2 NonEmpty.cons (OPTyp.oneM p) (OPTyp.manyM p)
~~~~
As I understand, `Applicative.some` must only be an optimization of `OP.liftA2 (:) p (OP.many p)`, not something else. That is, when using `Applicative.some` I assume that it does the same as the generic definition of `some` says. The current implementation of `some` should be a custom function of `Parser`, maybe implemented as `some p = adjustHelpAndMetavar p (Applicative.some p)`.

**Comment by HuwCampbell** [comment]
Thanks for writing, you are correct.
There's been a few discussions around this topic, including over here https://www.reddit.com/r/haskell/comments/2j8bvl/laws_of_some_and_many/ .
The crux is that optparse parsers must be able to be statically analysed – both for the production of the help text and the running of the parser (as terms are searched for across the entire parse tree).
Using the default implementation would yield an infinite parse tree and lead to a hang when run, as mentioned in #112, and an infinitely long usage text.
Unfortunately I know no way around this (nor believe that one is possible).

**Comment by amigalemming** [comment]
On Wed, 27 Apr 2016, Huw Campbell wrote:

> Thanks for writing, you are correct.
> There's been a few discussions around this topic, including over here
> https://www.reddit.com/r/haskell/comments/2j8bvl/laws_of_some_and_many/ .
> The crux is that optparse parsers must be able to be statically analysed – both for the production of the help text and
> the running of the parser (as terms are searched for across the entire parse tree).
> Using the default implementation would yield an infinite parse tree and lead to a hang when run, as mentioned in #112,
> and an infinitely long usage text.

I was afraid of that. Maybe it is not good to have 'some' and 'many' 
methods in the Alternative class then.

> Unfortunately I know no way around this (nor believe that one is possible).

Maybe using unsafePerformIO, but that is not much better.

**Comment by HuwCampbell** [comment]
Well, I don't think it's that bad. We have an implementation of some and many which works for our grammar. If we didn't, then it would make the Alternative instance essentially unusable.

I don't think there's anything actionable from this, so I'll close.

Thanks though :)
