### ISSUE TITLE
Better type for subcommand parser

### ISSUE THREAD

**Issue by amigalemming** [pcapriotti/optparse-applicative#201]
The current type of `subparser`
~~~~
subparser :: Mod CommandFields a -> Parser a
~~~~
suggests that you can have multiple subparsers on the same level or even have nested sub-commands. If you try to use this or do it accidentally, then the program runs but the parser gets confused. How about choosing a type that makes it clear what is allowed?

**Comment by HuwCampbell** [comment]
So one can have multiple subparsers on the same level, which is useful if some are to be hidden. I'm currently strongly considering using this functionality for command grouping as well (to improve the help texts in #197 ).

I've also used nested subcommands in my work, an example for git (if they used optparse) could be
`git submodule update`

I'm interested though, could you give an example where the parser gets confused?

**Comment by amigalemming** [comment]
On Mon, 2 May 2016, Huw Campbell wrote:

> I'm interested though, could you give an example where the parser gets confused?

Unfortunately, not. But if you make the functionality work, I am happy 
with it.
