### ISSUE TITLE
optparse-applicative-wx GUI

### ISSUE THREAD

**Issue by amigalemming** [pcapriotti/optparse-applicative#204]
This is a suggestion for a new package rather than an addition to optparse-applicative.
For some users the command line is rather fearsome. I thought it would be nice to have a library with an API almost identical to optparse-applicative that allows the following:

* Show a GUI that allows the user to enter all options in a graphical way.
* Allow the program to be started without GUI, with plain command-line options.
* Load and save the GUI contents from and to a bash script (or BAT file on Windows) with an equivalent command-line. This way, users can manage a protocoll on how they ran the program.

Of course, the GUI library would e.g. need additional information whether a string option is actually a path option for a file or a directory. In this case it would provide an according file requester that allows for selecting files, directories, maybe multiple of them. Because of this additional information I think such a GUI option library should be a wrapper around optparse-applicative.

Has anyone already thought or worked in this direction?

**Comment by HuwCampbell** [comment]
I've seen this one https://github.com/mxswd/webcloud
Also similar to #112

**Comment by HuwCampbell** [comment]
I don't think there's anything really actionable out of this issue, so I'll close.

Thanks for the suggestion though.
