### ISSUE TITLE
'hsubparser' overrides the command's metavar

### ISSUE THREAD

**Issue by TravisWhitaker** [pcapriotti/optparse-applicative#206]
`hsubparser` seems to unnecessarily override its argument's metavar. If I write something like:

```haskell
hsubparser $ mconcat [ command "cmd" (info args (progDesc "Some command.")
                     , metavar "cmd"
                     , help "Some command."
                     ]
```

The generated help for the enclosing command will show "COMMAND" instead of "cmd", which makes silly looking help messages like `(COMMAND | COMMAND | COMMAND ...)`.

This is a trivial change to the definition of `hsubparser` and I'd be happy to submit a PR; just wanted to make sure there's not some good reason for this default behavior that isn't obvious to me.

**Comment by TravisWhitaker** [comment]
This might be more interesting than I thought. `hsubparser` explicitly overrides the metavar:

```haskell
hsubparser :: Mod CommandFields a -> Parser a
hsubparser m = mkParser d g rdr
  where
    Mod _ d g = metavar "COMMAND" `mappend` m
    (cmds, subs) = mkCommand m
    rdr = CmdReader cmds (fmap add_helper . subs)
    add_helper pinfo = pinfo
      { infoParser = infoParser pinfo <**> helper }
```

`subparser` tries to do the same thing:

```haskell
subparser :: Mod CommandFields a -> Parser a
subparser m = mkParser d g rdr
  where
    Mod _ d g = metavar "COMMAND" `mappend` m
    rdr = uncurry CmdReader (mkCommand m)
```

Indeed, commit d26d2ec4be73761c6dc481 explicitly says "Let override subparser's metavar". However, if I write a parser like this:

```haskell
ex = subparser $ mconcat [ command "cmd1" (info (pure ()) (progDesc "command 1"))
                         , command "cmd2" (info (pure ()) (progDesc "command 2"))
                         , metavar "CMD"
                         ]
```

and run it with no arguments, the resulting error message is:

```
Missing: CMD
```

indicating that the "CMD" metavar was not overridden. If instead I write:

```haskell
ex = hsubparser $ mconcat [ command "cmd1" (info (pure ()) (progDesc "command 1"))
                          , command "cmd2" (info (pure ()) (progDesc "command 2"))
                          , metavar "CMD"
                          ]
```

and run it with no arguments, the resulting error message is:

```
Missing: COMMAND
```

indicating that the "CMD" metavar was overridden with "COMMAND".

The following illustrates my use case. Suppose I have the following parsers:

```haskell
ex :: Parser ()
ex = cmd1 <|> cmd2

cmd1 :: Parser ()
cmd1 = subparser $ mconcat [ command "cmd1" (info (pure()) (progDesc "command 1"))
                           , metavar "cmd1"
                           ]

cmd2 :: Parser ()
cmd2 = subparser $ mconcat [ command "cmd2" (info (pure()) (progDesc "command 2"))
                           , metavar "cmd2"
                           ]
```

The generated help for this parser knows that the only two options are cmd1 or cmd2:

```
Usage: Example (cmd1 | cmd2)
```

Suppose I'd like `cmd1` and `cmd2` to have their own sub-helps. Substituting `hsubparser` for `subparser` in the previous example yields the following usage message for the top-level parser:

```
Usage: Example (COMMAND | COMMAND)
```

Perhaps I'm abusing this functionality in the first place, but the inconsistency between `subparser` and `hsubparser` is strange.

**Comment by HuwCampbell** [comment]
#203 
I found and fixed this a few weeks ago, will be included in the next release.

**Comment by HuwCampbell** [comment]
The arguments are applied left to right, the "overridden" in that commit was referring to the user's input. So the user overrides the default of "COMMAND".
`hsubparser` did have it backwards (still does on hackage), so the user could not override the default.

**Comment by TravisWhitaker** [comment]
Ah, I see, thanks for the clarification.
