### ISSUE TITLE
duplicates in metavar option list

### ISSUE THREAD

**Issue by Fuuzetsu** [pcapriotti/optparse-applicative#208]
If we have a parser with multiple commands such that

```
$ foo --help
foo (COMMAND | COMMAND | COMMAND)

subcommands:
bar …
baz …
qux …
```

Ideally we'd see `foo ( bar | baz | qux )` but it's understandable that metavars are the only thing we can consistently list. But in that case, I would expect `foo COMMAND`, i.e. we shouldn't have duplicates in the list.

Spotted in version 0.12.1.0

**Comment by HuwCampbell** [comment]
You're writing each command in it's own subparser, which isn't necessary. From the examples:
```haskell
sample :: Parser Sample
sample = subparser
       ( command "hello"
         (info hello
               (progDesc "Print greeting"))
      <> command "goodbye"
         (info (pure Goodbye)
               (progDesc "Say goodbye"))
       )
```

**Comment by HuwCampbell** [comment]
You could also set the `metavar` to `bar`... if you're keen on the `( bar | baz | qux )` and keep them in their own subparsers.

It works either way.
