### ISSUE TITLE
Doc values are not word-wrapped

### ISSUE THREAD

**Issue by pseudometric** [pcapriotti/optparse-applicative#215]
When I use `progDesc`, the text is word-wrapped as I expect. However, if I use `progDescDoc` and a `Doc` value, the text is not wrapped: long lines just run on past the terminal width (80 or as set with `customExecParser . prefs . columns`). Am I missing something?

**Comment by HuwCampbell** [comment]
Not sure how your generating your `Doc` but at a guess I'd say that you're including one large string of text. The pretty printer by itself doesn't split text on spaces.

As one can see in the [doc for the pretty printer](https://hackage.haskell.org/package/wl-pprint-1.2/docs/Text-PrettyPrint-Leijen.html#g:3) it's common to use something like 
`fillSep . fmap text . words` if you want the text to be able to wrap on any space.

**Comment by HuwCampbell** [comment]
That help? Can I close this issue?

**Comment by pseudometric** [comment]
Yes, I missed that somehow; thanks!

**Comment by HuwCampbell** [comment]
No probs.
