### ISSUE TITLE
Example for ``parseFluxCapacitor`` confusingly uses ``Monad a`` instead of ``ReadM a``

### ISSUE THREAD

**Issue by kozross** [pcapriotti/optparse-applicative#218]
I don't quite understand the use of the added generality - it actually confused me quite a bit, because I couldn't think of exactly how you would indicate a 'failure state' against a general ``Monad`` (as I could with ``ReadM``). Would it be possible to rewrite the example signature to use ``ReadM`` instead?

**Comment by HuwCampbell** [comment]
I agree it's not the best example. I think I will change the example to use the `eitherReader` combinator. It's what most folks would find the simplest.

BTW:
```haskell
eitherReader :: (String -> Either String a) -> ReadM a
```

**Comment by HuwCampbell** [comment]
Please see #219.
