### ISSUE TITLE
Multiple command groups yield bad error message

### ISSUE THREAD

**Issue by nomeata** [pcapriotti/optparse-applicative#221]
I have started using `commandGroup` in [this commit](https://github.com/entropia/tip-toi-reveng/commit/8573ffec1f79bd65ea1fa9453845b867d4ff1968) and it works ok, with the exception of the error message when no command is given, and also the summary:

```
$ tttool
Missing: (COMMAND | COMMAND | COMMAND | COMMAND | COMMAND)

Usage: tttool [-t|--transscript FILE] [--code-dim W[xH]] [--dpi DPI]
              [--pixel-size N] (COMMAND | COMMAND | COMMAND | COMMAND | COMMAND)
  tttool-1.6.1.2 -- The swiss army knife for the Tiptoi hacker
[..]
```

and

```
$ tttool -- --help
Usage: tttool [-t|--transscript FILE] [--code-dim W[xH]] [--dpi DPI]
              [--pixel-size N] (COMMAND | COMMAND | COMMAND | COMMAND | COMMAND)
[..]
```

Any suggestions on how to avoid that?

**Comment by nomeata** [comment]
Ok, I have a work-around, see the commit linked above. If that is the best way of doing it, then this is merely a request for better documentation. If there is a better way, then, well, as well.

**Comment by HuwCampbell** [comment]
Currently there's not a better way, as one can have different `metavar`s for groups, or have subcommands which aren't alternatives.
Will add some doc.

**Comment by HuwCampbell** [comment]
I'm happy with the way this is documented now. Although I *could* put in a fix to combine these on opposite sides of an alternative I think it would be extremely flakey.
