### ISSUE TITLE
Removal of the mappend operator (<>)

### ISSUE THREAD

**Issue by svenkeidel** [pcapriotti/optparse-applicative#224]
Hi,

The newest release (0.13.0.0) of _optparse-applicative_ removed the mappend operator `(<>)` from the export list of `Options.Applicative`. This caused an [error](https://github.com/monto-editor/broker/issues/8) in my project since I did not import `(<>)` from `Data.Monoid` directly. Is there a particular reason why the operator got removed from the exports?

Best,
Sven

**Comment by HuwCampbell** [comment]
G'day,

Yes there is a reason. It's to do with the [Semigroup as a superclass of Monoid Proposal](https://ghc.haskell.org/trac/ghc/ticket/10365).

We are now exporting `Semigroup` instances for our `Monoid` datatypes. It didn't make sense to export the `Data.Monoid` version anymore, as people will have to hide it if they want to do the right thing (and the prelude will likely add semigroup's `(<>)` in 8.2).

Cheers,
Huw
