### ISSUE TITLE
Question: is it possible to add a footer to the standard help text?

### ISSUE THREAD

**Issue by edsko** [pcapriotti/optparse-applicative#225]
We'd like to be able to add something like

```
Use --help for more detailed information about all these options"
```

when the command line parser fails (but the user does not specify --help).

**Comment by HuwCampbell** [comment]
This is not a supported feature.

One could do this however using `execParserPure` and a quick re-implementation of `handleParseResult` to add custom details to the message.

If you think it's worthwhile and can come up with a way to support it without breaking compatibility, I'm always happy to look at PRs.

**Comment by HuwCampbell** [comment]
Actually, I believe it's simpler, such that I can say yes it's supported, just using `execParserPure`, `handleParseResult` and `overFailure` to add the footer.

**Comment by edsko** [comment]
Awesome, great. Thanks! :)
