### ISSUE TITLE
QuickCheck 2.9.2 support

### ISSUE THREAD

**Issue by bergmark** [pcapriotti/optparse-applicative#228]
optparse-applicative's test suite will be disabled in stackage because of the `QuickCheck < 2.9.2` upper bound, can you please ping me if a fix gets released? Thanks!

**Comment by HuwCampbell** [comment]
G'day,
For a few months now, we've had deps on quickcheck as
`QuickCheck >= 2.8 && < 2.11`
Stackage however, doesn't support the latest optparse-applicative.
I don't think this is a bug on my end.
Cheers,
Huw

**Comment by HuwCampbell** [comment]
Sorry, I wasn't correct with that comment, the QuickCheck bounds were changed a few weeks ago.

I can release a 0.13.1 with them, but as stack is on 12.1, I'm not sure it will help.

**Comment by bergmark** [comment]
We have since added a new mechanism to notify us of new releases so issues like this aren't needed anymore. We can just add an entry there for optparse-applicative if the test suite hasn't been updated when we lift the upper bound.

So there's no rush to get his released for our sake, thanks!

**Comment by DanBurton** [comment]
Just bumping this issue.

It would, in fact, allow us to run the optparse-applictive test suite on stackage nightly builds if you were to release 0.13.1 with the relaxed bounds on QuickCheck. If it's convenient for you, I do recommend making the release for this reason.
