### ISSUE TITLE
(<|>) doesn't work with positioned arguments

### ISSUE THREAD

**Issue by k0ral** [pcapriotti/optparse-applicative#229]
Here's a minimal code to reproduce:

```haskell
import Control.Applicative
import Options.Applicative.Builder
import Options.Applicative.Extra
import Options.Applicative.Types

data A = A1 Int | A2 String
  deriving(Show)

parser :: Parser A
parser = (fmap A1 $ argument auto mempty) <|> (fmap A2 $ strArgument mempty)

main :: IO ()
main = print =<< customExecParser defaultPrefs (info parser mempty)
```

I would expect this code to parse a single argument that is either an integer or a string.
Here is how it actually behaves:

```
> executable 1
A1 1

> executable HELLO
cannot parse value `HELLO'
```

Did I miss something, or is that a bug ?

**Comment by HuwCampbell** [comment]
Please see https://github.com/pcapriotti/optparse-applicative/issues/166

**Comment by HuwCampbell** [comment]
One more hint for you though... although I believe that it's best practice to keep logic out of the ReadM functions, one can use the fact that they do have Alternative instances to do something like this
```
parser = argument (A1 <$> auto <|> A2 <$> str) mempty
```
