### ISSUE TITLE
Overlapping flags and options or options with optional arguments

### ISSUE THREAD

**Issue by ollef** [pcapriotti/optparse-applicative#235]
Hey, and thanks for an excellent library!

Is there any way to get a `-v` flag working on its own but also allow passing it an argument, such as `-vn`?

Many command-line utilities support this idiom (e.g. `ghc`), but I haven't been able to get it to work with `optparse-applicative`. I tried the following (and a few different variations):

```
option auto
    (long "verbose"
    <> short 'v'
    <> metavar "LEVEL"
    <> help "Set the verbosity level to LEVEL")
<|>
flag 0 1
    (long "verbose"
    <> short 'v'
    <> help "Enable verbose mode")
```

but it seems like the `option` takes precedence.

Cheers!

**Comment by HuwCampbell** [comment]
Cheers.
No, there isn't a way to do this by design, as this situation can lead to an ambiguous parse. Please see #194 for more of an explanation.

**Comment by ollef** [comment]
Alright, I guess I'll have to live with the argument form then.

Feel free to close the issue if it won't happen. Thanks for your reply!

Perhaps this should be documented?

**Comment by HuwCampbell** [comment]
I'm adding this to the README
