### ISSUE TITLE
Use Semigroup constraint on Monoid instance for Chunk

### ISSUE THREAD

**Issue by expipiplus1** [pcapriotti/optparse-applicative#236]
Now that Semigroup is in base the instance for `Monoid (Chunk a)` the instance could be relaxed to `Semigroup a => Monoid (Chunk a)` from `Monoid a => Monoid (Chunk a)`

**Comment by HuwCampbell** [comment]
Indeed, would fit the purpose of a free monoid on a semigroup better.

**Comment by HuwCampbell** [comment]
Problems start emerging though as `Text.PrettyPrint.ANSI.Leijen.Doc` doesn't have a `Semigroup` instance, and is the actual use case for `Chunk`.
I'll keep an eye on that library and update when possible, closing for now though.
