### ISSUE TITLE
Alternative parser instance doesn’t produce very user-friendly messages

### ISSUE THREAD

**Issue by Profpatsch** [pcapriotti/optparse-applicative#238]
I described the problem  in https://github.com/Gabriel439/Haskell-Optparse-Generic-Library/issues/29#issuecomment-266894024, where `optparse-generic` is just a thin wrapper that generically creates argument parsers from data types.

**Comment by HuwCampbell** [comment]
We have `multiSuffix` which is often used to put a '...' or something to that effect in the help text.
