### ISSUE TITLE
No instance for (Options.Applicative.Builder.Internal.HasName  ArgumentFields)

### ISSUE THREAD

**Issue by andrewufrank** [pcapriotti/optparse-applicative#246]
i import  (following the example) in stack with lts 8.2
````
import           Data.Semigroup              ((<>))
import           Options.Applicative
import           Options.Applicative.Builder

...
cmdArgs :: Parser LitArgs
cmdArgs = LitArgs
     <$> argument str
          (long "subdir" <> metavar "STRING"
         <> help "subdirectory name" )
     <*> argument str
          ( long "filename" <> metavar "STRING"
         <> help "filename " )
     <*> argument str
          ( long "project" <> metavar "STRING"
         <> help "project name, default subdir name" )
     <*> argument str
          ( long "buch" <> metavar "STRING"
         <> help "buch name, default subdir name" )
     <*> argument str
          ( long "language" <> metavar "STRING"
         <> help "language, default English" )
````
and get the error when i use long :
/home/frank/Workspace8/repo8/litMain/LitMain/CmdLine.hs:47:12: error:
        • No instance for (Options.Applicative.Builder.Internal.HasName
                             ArgumentFields)
            arising from a use of ‘long’
        • In the first argument of ‘(<>)’, namely ‘long "subdir"’
          In the second argument of ‘argument’, namely
            ‘(long "subdir" <> metavar "STRING" <> help "subdirectory name")’
          In the second argument of ‘(<$>)’, namely
            ‘argument
               str
               (long "subdir" <> metavar "STRING" <> help "subdirectory name")’

what is wrong in my code?

**Comment by HuwCampbell** [comment]
Positional arguments aren't specified with long or short options, so you can't use those builders.

If you want your program to be specified with
```
myprogram --subdir here --filename this --project foo --buch bar --language french
```
then you should be using `option` instead of `argument`.

If you want it to be
```
myprogram here this foo bar french
```
then remove the `long` builder.

**Comment by andrewufrank** [comment]
thank you - i did not understand this from the simple example and saw only now, that there is a much longer and more detailed description. i will read!
