### ISSUE TITLE
Include a haskell implementation of path completion?

### ISSUE THREAD

**Issue by mgsloan** [pcapriotti/optparse-applicative#252]
I've implemented path completion in Haskell, here: https://github.com/commercialhaskell/stack/blob/24ba0acb22e8e400dc9941e39dbd35b9b9f6fd87/src/Options/Applicative/Builder/Extra.hs#L180

Why is this better than `action "file"`  or `action "directory"`?

* They break horribly when typing something like `"a/quoted/path`.  I'd suggest deprecating action or fixing its quoting behavior.
* Allows separate filtering of files and dirs - useful for filtering down files to specific extensions.
* Faster!

Perhaps something like this should be added to optparse-applicative?

**Comment by HuwCampbell** [comment]
Hmm, I hadn't seen that quote bug before, that's definitely something to fix, your unescape function might help there too.

I'm pretty open to good completions without punching out to Bash, so thanks for the heads up.

**Comment by HuwCampbell** [comment]
Hey @mgsloan,
I started with your escaping function and fixed up those bugs with quoted paths, so thank you very much for pointing me to that. It also fixed the tilde expansion which had been bothering me.

I'm tempted towards leaving it at that for now, as I don't want to confuse people having two functions which do similar things.

Huw

**Comment by mgsloan** [comment]
@HuwCampbell Cool, glad it helped!
