### ISSUE TITLE
No Stack ?

### ISSUE THREAD

**Issue by Raveline** [pcapriotti/optparse-applicative#263]
Sorry if this is a beginner question, but I'm surprised that there seems to be no stack.yaml file to build the lib. I had no issue when doing a stack init on my own. I know that optparse-applicative is a dependency for Stack itself, but so is Conduit that comes with its own Stack file, so I'm not sure there is any circular-dependency problem here.

Is there any reason for the lack of Stack file ?

**Comment by HuwCampbell** [comment]
I don't want to tie `optparse-applicative` to stack or its curated snapshots. It could paper over real problems for cabal users (of which there are many).

As you said, it's easy to build `optparse-applicative` with stack, as it is with cabal (and mafia). I'd like to keep it that way.

**Comment by Raveline** [comment]
Ok, I understand ! Thanks for clarifying this and sorry for bothering you !
