### ISSUE TITLE
Distinguish between arguments before and after `--`

### ISSUE THREAD

**Issue by benma** [pcapriotti/optparse-applicative#269]
Hi

In https://github.com/commercialhaskell/stack/issues/2210, we are dealing with the issue that we have two sets of `many strArgument` that we need, the ones before ` -- ` and the ones after ` -- ` - the latter to pass along to other binaries which are wrapped.

Is it possible to distinguish between those two sets of positional arguments? Reading the docs it seems like `strArgument` etc., don't care about this boundary.

Thank you already for any hints.

**Comment by HuwCampbell** [comment]
That's correct, it doesn't care about the boundary, the first `many argument` parser will greedily consume all that it can. I'm not really sure, one could use the `forwardOptions` builder, but as Greg says, it's not for all cases, and can lead to ambiguity and worse error messages if there are many flags to consider.

**Comment by benma** [comment]
Thanks. Would you consider adding a way to distinguish those if needed?

`forwardOptions` just bundles all "unused" ones, right? Forwarding them to the wrapped binary is unfortunately not future proof, as you noted (ambiguity).

**Comment by benma** [comment]
I understand. Thanks for your input!
