### ISSUE TITLE
Option groups, à la command groups

### ISSUE THREAD

**Issue by matthew-piziak** [pcapriotti/optparse-applicative#270]
We can group commands with the `commandGroup` option. Can we do the same with options? I have rather a lot of them and would like to separate them with whitespace and headings.

Hopefully this is already possible and I just missed it in the docs.

Thank you!

**Comment by HuwCampbell** [comment]
Not at the moment, I only added command groups recently and haven't generalised it.

There's this #231 PR up, but I haven't had the time to go through and offer all my thoughts.

**Comment by matthew-piziak** [comment]
Thanks for the status update! Let me know if there's any way I can help. This is something I would love to use downstream. :)

**Comment by infinity0** [comment]
Just adding my voice in favour of this feature. :) Sadly #231 was closed :(
