### ISSUE TITLE
Options with multiple arguments

### ISSUE THREAD

**Issue by wdanilo** [pcapriotti/optparse-applicative#271]
Hi!
Is it possible to parse options with multiple arguments using optparse?
Of course we are easily able to express it using applicative style, like:

```
multiArg = (,) <$> strOption   (hidden <> long "pass" <> metavar "switch name" <> help "Switch passes execution.")
               <*> strArgument (internal <> metavar "name")
```

which works fine, but as noted in the example code, we have to use `internal` modifier because this option is wrongly displayed in both help and usage without it. But it is not the proper solution for this problem, unfortunatelly. When using `internal` modifier, when the option is not provided we get an error `Missing:` which is not helpful at all. 

PS. The metavar I use above "switch name" is just hack to display metavar of first arg and second arg when the second is hidden by `internal` modifier.

**Comment by HuwCampbell** [comment]
It's not a supported use can no, as it's not really conforming with the unix command line conventions.

I don't know your use case, but if it's a configuration map or something similar, you might want to try a parser with `[-c name=value]`; a comma or colon separated list is also a common. It's easy to write these with `eitherReader` and Parsec (or friends).

**Comment by wdanilo** [comment]
I understand it is not "standatd" unix command syntax, however it is possible to easily create such construction using the Applicative interface. This library is not called "optparse-unix" and I thought that everything we can create using applicatives should be supported here. In fact the above formula is a very simple one and the generated help text is just inappropriate, so I still think we should consider this as a bug. I will however understand if you've got another opinion in this topic – then we can close this issue.

**Comment by HuwCampbell** [comment]
The parser you've specified is indeed allowed and makes sense, but it's not an option which takes two arguments. Rather, it's a positional argument and an option. Options can go before or after the positional argument (with noIntersperse on) and be written in any order with other options. So a user can write
```
program helpValue --pass switchValue
```
or
```
program --pass switchValue --someOtherFlag helpValue
```
instead of
```
program --pass switchValue helpValue
```
and all are equally valid (which is the intentional behaviour of options and arguments in the library).

Does that make sense?

**Comment by HuwCampbell** [comment]
Feel free to follow up
