### ISSUE TITLE
Help printing command

### ISSUE THREAD

**Issue by wdanilo** [pcapriotti/optparse-applicative#272]
Hi!
Is it possible to create a subcommand that will behave like helper? 
In onther words, in my optparser I would like to be able to write `myapp install help`, which would behave like `myapp install --help`.

**Comment by HuwCampbell** [comment]
GHC mod has an example of how to obtain that behaviour (I've edited it a bit to provide better error messages).

https://github.com/HuwCampbell/ghc-mod/blob/7e22ea5c782259feb21d9c9675f964b57ab1adf2/src/GHCMod/Options.hs#L53-L69

**Comment by wdanilo** [comment]
I see, cool, thank you for your help! Don't you think it should be described in the help? This solution is hacky!

**Comment by HuwCampbell** [comment]
It is hacky yes. Which is why I haven't incorporated it into the help.
