### ISSUE TITLE
Quoted option values?

### ISSUE THREAD

**Issue by portnov** [pcapriotti/optparse-applicative#278]
Is it possible to parse command lines like `--foo "two words"` ?
I have a custom reader for my option, if it matters.

**Comment by portnov** [comment]
Hm, it seems optparse-applicative somehow parses quoted values correctly when they are passed directly from command line.
But, under some circumstances, I have to use execParserPure on some input string. execParserPure requires `[String]`; for now, I do pass (words string), which is obviously incorrect for quoted values.

So the question becomes: is there somewhere exported parser of String -> [String], which handles quotes the same way as command line?

**Comment by HuwCampbell** [comment]
Argument quoting is taken care of by your shell (probably bash, but all of them handle this).

If you call `getArgs` it will give the arguments to you quoted correctly (it's all we do).
