### ISSUE TITLE
Allow to override binary name in usage string

### ISSUE THREAD

**Issue by Xion** [pcapriotti/optparse-applicative#280]
Right now, it seems that `getProgName` is always used to obtain the binary name to display in usage string (and `--help` output). This works fine in most situations, but not when the program is to be invoked in a non-standard way (e.g. Stack plugin).

I suggest adding an explicit option (most likely to `ParserInfo`) to override the displayed binary name. For some additional rationale, check equivalent libraries in other languages which already implement this feature:
* [clap](https://docs.rs/clap/2.27.1/clap/struct.App.html#method.bin_name) for Rust
* [argparse](https://docs.python.org/release/2.7/library/argparse.html?highlight=argparse#prog) for Python

If this is an acceptable enhancement, I'm happy to prepare the PR myself.

**Comment by HuwCampbell** [comment]
Hmm, I'm not totally against more preference options, but `System.Environment` has the function `withProgName` which will probably do the job for you.

```haskell
withProgName "my-plugin" $ execParser p 
```

Is that acceptable?

**Comment by Xion** [comment]
Huh. I must have missed it! Yeah, it definitely works out well enough, as I tend to wrap `execParser` calls anyway. Thanks!
