### ISSUE TITLE
More control over help output

### ISSUE THREAD

**Issue by erikd** [pcapriotti/optparse-applicative#283]
While working on https://github.coom/erikd/jenga I tried to add a help message using:

```
  , subCommand "init"
      ( "Initialize a project to be built with Mafia. Specifically that means:\n"
      <> "  * Add all git locations in the stack file as git submodules\n"
      <> "  * Find all the cabal files that are not submodules and generate a lock file for each\n"
      <> "This command assumes that it is being run in a Git repo and that that 'stack.yaml' file is in the top level directory of the Git repo."
      <> "This command will also generate a '.jenga' file in the top level directory.")
      (Initialize <$> subModulesDirP)
```
and was hoping to get output along the lines of:
```
Initialize a project to be built with Mafia. Specifically that means:
  * Add all git locations in the stack file as git submodules.
  * Find all the cabal files that are not submodules and generate a lock file for each.
This command assumes that it is being run in a Git repo and that that 'stack.yaml'
file is in the top level directory of the Git repo.
This command will also generate a '.jenga' file in the top level directory.
```
but optparse just concatenates all the strings and then imposes its own line breaks which is not what I intended.

I tried replacing the `<>` operator with `<$$>` from `Text.PrettyPrint.ANSI.Leijen` but the types are wrong.

Is there a way to do this so I have more control over layout?

**Comment by HuwCampbell** [comment]
`subCommand` isn't an `optparse-applicative` builder but rather something you have defined inline.

Looks like you've used `progDesc` within its definition, while `progDescDoc` might be what you're after.

**Comment by erikd** [comment]
Yep, thanks. `progDescDoc` is what I need.
