### ISSUE TITLE
Support for recent versions of QuickCheck?

### ISSUE THREAD

**Issue by peti** [pcapriotti/optparse-applicative#288]
Would you consider releasing an update that supports QuickCheck-2.11.3? This is necessary to compile with GHC  8.4.x, for example.

http://packdeps.haskellers.com/feed?needle=optparse-applicative

**Comment by HuwCampbell** [comment]
Hi, yes. I have a PR up #287 for that already. I will push up a new version this week.

**Comment by HuwCampbell** [comment]
Done

**Comment by peti** [comment]
Thank you very much!
