### ISSUE TITLE
How to create sub-sub-commands

### ISSUE THREAD

**Issue by codygman** [pcapriotti/optparse-applicative#296]
For instance, the `aws` command has:

- `aws s3 ls s3://address`
- `aws s3 cp s3://address`

It seems these would make the most sense as sub-commands of sub-commands rather than some large data type containing a bunch of unrelated stuff.

It's not immediately clear how to accomplish this with subparser.

**Comment by HuwCampbell** [comment]
Hi,
Yep, it should be sub-commands of sub-commands.

Using `subparser` should be very easy, the internal ParserInfo just needs to also be a `subparser`

```haskell
subparser
  ( command "s3" (info s3Commands ( progDesc "S3 things" )))
    where
      s3Commands = subparser (command "ls" s3Ls ( progDesc "List a bucket" )))
```

**Comment by HuwCampbell** [comment]
Feel free to follow up if you've any questions.

**Comment by codygman** [comment]
Hi Huw,

This answered my question.

Thanks!
