### ISSUE TITLE
Documentation at Hackage says "Page not found"

### ISSUE THREAD

**Issue by ChandraKoduru** [pcapriotti/optparse-applicative#297]
Hi,

The documentation at [hackage](https://hackage.haskell.org/package/optparse-applicative-0.14.2.0/optparse-applicative-0.14.2.0/src#introduction) for optparse-applicative is not working. It says "Page not found"

The documentation is **available** at [github](https://github.com/pcapriotti/optparse-applicative#introduction)

**Comment by HuwCampbell** [comment]
This you've messed up your link
https://hackage.haskell.org/package/optparse-applicative
works fine.

**Comment by LucianU** [comment]
@HuwCampbell try clicking on one of the links in the README (on the Hackage page). It will take you to "Page not found".

**Comment by HuwCampbell** [comment]
Looks like a hackage bug in their markdown rendering.
