### ISSUE TITLE
Make `showHelpOnError` show help text for subcommand not top-level command on error

### ISSUE THREAD

**Issue by sseefried** [pcapriotti/optparse-applicative#298]
Let's say I'm creating a utility called `my-tool`
Say I have a `ParserInfo` value defined as:

```Haskell
parserInfo = info (options <**> helper) fullDesc
  where
    options = hsubparser (cmd1 <> cmd2)
```
where `cmd1` and `cmd2` are subparsers  with their own helpers defined.

e.g.
```Haskell
cmd1 = command "cmd" $ info (cmd1Parser <**> helper) fullDesc
```

Let's say I execute the parser with `customExecParser (prefs showHelpOnError) parserInfo`

Now let's say that, on the command line, I type something like:

```
$ my-tool cmd1 --some-flag-not-in-cmd1-parser
```

This produces an error. Unfortunately, what I'm seeing in the error output is something like this:

```
Invalid option `--some-flag-not-in-cmd1-parser'

Usage: my-tool COMMAND

Available options:
  -h,--help                Show this help text

Available commands:
  cmd1                Some description for cmd1
  cmd2                Some description for cmd2
```

I am seeing the help for the whole command, but what I actually want to see is the help for `cmd1`.
Is there some way for me to get this behaviour?

**Comment by HuwCampbell** [comment]
I'll first explain what's happening here.

The default behaviour for optparse is backtracking once a subcommand is completed. So if cmd1 is "complete", meaning it has no more mandatory parsers to fill, any unrecognised options will cause the sub-parser to exit, to be tried by the parent parser. In your case the parent also can't find it, so the help message is emitted there.

This allows things like global options to be passed in after the subcommands, or multiple subcommands to be specified.

So you can turn off backtracking if you don't need it, and you'll only see the cmd1 usage.

**Comment by HuwCampbell** [comment]
I'll close this, but feel free to follow up.

**Comment by sseefried** [comment]
Thanks @HuwCampbell. I'll try this out on Monday.

**Comment by sseefried** [comment]
I wonder if we can put this in the documentation somewhere as it requires quite a bit of knowledge of how the generated parsers work to work this out.  Thoughts?

**Comment by moll** [comment]
I noticed there's also `SubparserInline` in http://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative-Types.html#t:Backtracking that seems to lack a description.

**Comment by HuwCampbell** [comment]
http://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative.html#v:subparserInline

**Comment by moll** [comment]
Ah, great. Thanks. I was looking at http://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative-Types.html#t:Backtracking as that's where the `PrefsParser` definition (http://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative.html#t:ParserPrefs) led me.

**Comment by moll** [comment]
I suppose that's the negative of the monoidal style — there are two ways to configure and two places to look for documentation. ^_^

**Comment by moll** [comment]
Hehe, curiously, a year later I was confused by the same documentation problem — I clicked on `Backtracking` when viewing `ParserPrefs` (https://hackage.haskell.org/package/optparse-applicative-0.16.1.0/docs/Options-Applicative.html#t:ParserPrefs) and ended up looking at the data structure with no documentation, puzzled by what does backtracking mean. I really think the backtracking documentation should be visbile next to the data structure, too, as that's more likely to be discovered than the monoidal helper. How would anyone know there's a monoidal helper to look at (or why should search for it if they API takes data directly) if they're starting from the "Running parsers" section (https://hackage.haskell.org/package/optparse-applicative-0.16.1.0/docs/Options-Applicative.html#g:9).
