### ISSUE TITLE
Multi-word strings not parsed as one, but multiple

### ISSUE THREAD

**Issue by Supernerd11** [pcapriotti/optparse-applicative#301]
As the title suggests, instead of parsing an argument like `"this one"` as one, it parses it as two words: `"this"` and `"one"`. This causes an error, and is not what I would think is intended behaviour.

**Comment by HuwCampbell** [comment]
I'm certain you're not hitting an optparse issue here. CLI programs should not split or join arguments passed to them, and optparse as a library does not do this at all.

Shell arguments passing to binaries is handled entirely by your shell, be it bash, sh, zsh, etc.

**Comment by Supernerd11** [comment]
Apparently this is a stack-run bug...
