### ISSUE TITLE
Bash autocompletion doesn't work with multiple commands

### ISSUE THREAD

**Issue by ChShersh** [pcapriotti/optparse-applicative#305]
Autocompletion doesn't work for each command (only for first one) when I have multiple different commands at the same time.

Here is recorded demo of behavior:

[![asciicast](https://asciinema.org/a/JUtqO6HnoaSvue0OCwLMDecaG.png)](https://asciinema.org/a/JUtqO6HnoaSvue0OCwLMDecaG)

And here is minimal code:

```haskell
module Main where

import Data.Semigroup ((<>))
import Options.Applicative (Parser, ParserInfo, command, execParser, fullDesc, helper, info,
                            metavar, optional, progDesc, subparser)

main :: IO ()
main = execParser prsr >>= print

data Options = Options (Maybe ()) (Maybe ())
    deriving Show

fooP :: Parser ()
fooP = subparser $ mconcat
    [ metavar "foo [OPTIONS]"
    , command "foo" $ info (helper *> pure ()) (progDesc "Foo")
    ]

barP :: Parser ()
barP = subparser $ mconcat
    [ metavar "bar [OPTIONS]"
    , command "bar" $ info (helper *> pure ()) (progDesc "Bar")
    ]

optsP :: Parser Options
optsP = Options <$> optional barP <*> optional fooP

prsr :: ParserInfo Options
prsr = info (helper <*> optsP) $ fullDesc <> progDesc "Completion example"
```

**Comment by HuwCampbell** [comment]
This is the correct behaviour. Your subcommands both need to be entered, one after the other. So to make your program run, you need to type.
```
foo-bar foo bar
```

Typing
```
foo-bar foo
```
is an error, so we don't suggest it.

Make sense?

**Comment by HuwCampbell** [comment]
If you're struggling to write what you want maybe check out the [commands section](https://github.com/pcapriotti/optparse-applicative#commands)  of the readme.

I'll close this, but feel free to follow up with any questions.

**Comment by ChShersh** [comment]
@HuwCampbell Doesn't make sense. I don't need both of my subcommands to be specified since they're written with the help of `optional`. In my real use case I has bunch of ternary flags. Those flags can be in on of three states:

1. Enabled.
2. Disabled.
3. Not specified.

I like the fact that I can join multiple single-letter flags into single flag. So instead of writing:

```bash
foo -g -f -b -t
```

I can just write

```bash
foo -gfbt
```

But such flags has semantic of `Bool` (either specified or not specified) where in reality I want `Maybe Bool`. So we've used the following approach to achieve desired behavior and interface:

```bash
my-command with -gtf without -leb
my-command with -gtf # this is correct command
my-command without -leb # also correct command
```

This looks very convenient but autocompletion doesn't work 😞 Even if both `with` and `without` are specified, autocompletion always suggests only one command.

**Comment by HuwCampbell** [comment]
I understand. Yep, it looks like my logic for reachable completions has a flaw in how it handles optional commands.
I'll have a look at getting a fix done.

**Comment by HuwCampbell** [comment]
Please check out #306, should fix this problem.
