### ISSUE TITLE
Add Eq instance to ParserResult

### ISSUE THREAD

**Issue by jonringer** [pcapriotti/optparse-applicative#309]
I would like to test the that my opts structure gets filled out correctly. execParserPure seems like the right tool for the job, however, there's no way to really do an assertion against it without an Eq instance.
```haskell
import Options.Applicative
import Test.Hspec

p = execParserPure defaultPrefs $ info myProgOpts briefDesc
testCLI =  it "parses it correctly" $ do
                      p ["--summary"] `shouldBe` (Success (Summary True))
```
Although the example is quite trivial, it still seems really useful for preventing regressions if you're modifying your opts struct, or testing more complicated parsing logic.

**Comment by jonringer** [comment]
A rather ugly solution to this would be to have a Eq case for the Success constructor, but leave the other two computations to be false. I don't like it the instance below (because its unsound), but i guess it would work in my case to verify that something is correctly parsed. Unless I'm missing some other way to go about this.

```haskell
instance (Eq a) => Eq (ParserResult a) where
  Success a == Success b = a == b
  _ == _ = False
```

**Comment by HuwCampbell** [comment]
I don't think adding an `Eq` instance is the right thing to do here. `optparse` does however have a test suite which includes quite a lot of assertions about its runtime behaviour. So it's certainly possible without one.

Have you considered a simple function like this? (It's for quickcheck, but it should be trivial to port to `Hspec`).

```haskell
assertResult :: ParserResult a -> (a -> Property) -> Property
assertResult x f = case x of
  Success r -> f r
  Failure e -> do
    let (msg, _) = renderFailure e "test"
    counterexample ("unexpected parse error\n" ++ msg) failed
  CompletionInvoked _ -> counterexample "expected result, got completion" failed
```

**Comment by jonringer** [comment]
That's fair, when trying to create the Eq instance, it was made apparent it was never intended to be equatable in the first place; thus, should have a broken instance of one. 

Doing a small helper function to do the assertion is more than okay, i guess i was just curious if an Eq instance was possible but I was missing something about the two other cases.

If there's enough value in the helper functions, I could always do something similar to [Test.Hspec.Megaparsec](https://hackage.haskell.org/package/hspec-megaparsec-1.0.0/docs/Test-Hspec-Megaparsec.html)

I appreciate the response, I'll close the ticket as the issue is no longer relevant. Thank you @HuwCampbell
