### ISSUE TITLE
Make `helper` column length configurable

### ISSUE THREAD

**Issue by Fuuzetsu** [pcapriotti/optparse-applicative#311]
Currently if we use the `helper` function, it will go through `Show` instance which renders the underlying `Doc` with 80 column argument. It'd be nice if there was a version where this can be specified.

**Comment by HuwCampbell** [comment]
This doesn't sound right to me. Using `helper` doesn't touch show, it invokes the usual error code path.

Could you point to the line of code or give a better example of behaviour you think isn't working?

**Comment by Fuuzetsu** [comment]
I haven't traced it exactly. Can you explain how we cam invoke helper with custom column width? I'm not at a computer at the moment...

**Comment by Fuuzetsu** [comment]
I'll try that and re-open if I still have a problem. Thanks.
