### ISSUE TITLE
`Parser` seems to break left-identity `Alternative` law

### ISSUE THREAD

**Issue by matthew-piziak** [pcapriotti/optparse-applicative#314]
To my surprise, I was able to make a parser work by simply flipping `combinedParser = fooParser <|> barParser` to `combinedParser = barParser <|> fooParser`. In this case `fooParser` was failing, but I would expect it to fail over to `barParser` according to the monoid laws for `Alternative`. `Parser` appears to be specifically breaking the left identity law. Do you know about this, or would you like me to make you a minimal example?

**Comment by HuwCampbell** [comment]
Failing on a `ReadM` error? This is not equivalent to `empty` (and actually can't be if making a consistent command line parser). See the third bullet point in https://github.com/pcapriotti/optparse-applicative#faq

Actually, I would prefer if `Parser` was not an instance of `Alternative` at all, but rather an instance of `Alt` from semigroupoids; but it would be a terrible move while it's not a super class of `Alternative`.

**Comment by matthew-piziak** [comment]
@HuwCampbell Thank you! I will reconfigure my parser to match. Thanks for teaching me.
