### ISSUE TITLE
Providing an infoOption argument triggers showHelpOnError

### ISSUE THREAD

**Issue by seagreen** [pcapriotti/optparse-applicative#321]
I like using `showHelpOnError`, but it has the drawback that it makes the help text appear when the user provides an `infoOption`. For instance, if you have a `--version` InfoOption that shows the program's version, `showHelpOnError` will print the entire help text after the version number, which even though there hasn't actually been an error.

I have a one-liner here that fixes this behavior: https://github.com/seagreen/optparse-applicative/commit/e5265b58aa9a5a660fcdd23afcdaff942835f791

*However* I don't actually like it. The core problem is that aborting with an `InfoMsg` is implemented as a `ParseError`, when it really isn't an error at all.

Any thoughts on how to fix this? `ParseError` could be renamed to something like `Abort`, but I have no idea whether that's feasible or not due to backwards compatibility concerns.

**Comment by HuwCampbell** [comment]
Nomenclature aside, I think the _behavior_ you suggest is actually better than what we currently provide.

**Comment by HuwCampbell** [comment]
I've cherry picked your commit in, as behaviorally I agree this is better behaviour. Nomenclature can be discussed separately, but I don't think it's a big issue.
