### ISSUE TITLE
Equality sign in help

### ISSUE THREAD

**Issue by googleson78** [pcapriotti/optparse-applicative#327]
Is it possible to have a flag which modifies how long options are printed.
More specifically I'm talking about this:

Currently if you have a long option `foo` with an argument `ARG1` it will display as:
```
--foo ARG1
```
in the `--help`. But both `--foo arg1` and `--foo=ARG` parse correctly. Furthermore in most linux (unix?) utilities long options with arguments are set with `=` (in my experience at least). Is it possible to add a modifier/parser pref which will instead display `foo` as:
```
--foo=ARG1
```
in `--help`?

**Comment by HuwCampbell** [comment]
This seems reasonable.

**Comment by HuwCampbell** [comment]
So I've had a bit more of a think about this one. While it might be plausible to implement this, I think it may interact strangely when we have multiple names for an option.

For example
```
(-f|--foo ARG)
```
is fine, and both `-f ARG` and `--foo ARG` work. But `-f=ARG` isn't ok. So I don't think we should say it is.

**Comment by benjaminselfridge** [comment]
I ran into the same issue when implementing this feature -- what's the appropriate way to handle multiple names, when some are short and some are long? This snippet from `man ls` may be a guide:

```
       -T, --tabsize=COLS
              assume tab stops at each COLS instead of 8
```

So `man` sometimes lists multiple names for options by putting the equals sign after the long one and not the short one. I think users can be expected to know what this means. I think writing

```
(-f|--foo=ARG)
```

in the usage string is probably clear to most people as well, although perhaps a bit less so. I think it would be worth experimenting with.

**Comment by benjaminselfridge** [comment]
Experimented with this tonight -- see #336

**Comment by HuwCampbell** [comment]
Done and part of 0.15.0.

Thanks @benjaminselfridge and @googleson78
