### ISSUE TITLE
support the parsing of negative numbers as values passed to arguments?

### ISSUE THREAD

**Issue by chessai** [pcapriotti/optparse-applicative#337]
there seems to be no way to do this.

**Comment by evanrelf** [comment]
Does quoting help? e.g. `command --option "-1"`

**Comment by HuwCampbell** [comment]
You should also be able to use `--` to inform the parser that every following word is an argument.

So `-- -1` will be treated as the negative number 1.

Apart from that, I'm not sure how I could disambiguate in a way which wouldn't cause problems.

**Comment by HuwCampbell** [comment]
You should also be able to wrap negative numbers in parenthesis if you quote.

**Comment by pcapriotti** [comment]
This does not seem to be an issue. Closing.
