### ISSUE TITLE
Bash completion options

### ISSUE THREAD

**Issue by fgaz** [pcapriotti/optparse-applicative#338]
There are some useful completion options, particularly the `nospace` one, but it's not possible to use them with `optparse-applicative` as far as I know

**Comment by HuwCampbell** [comment]
So there's kind of two halves to the optparse completion puzzle. The scripts (be it bash, zsh, or fish) and the programmatic completions.

Options like `nospace` would be in the bash completion script, which are very small and can be edited and distributed with your binaries. If that's not good enough, I could probably add an argument to the `bash-completion-script` option which allows one to specify the arguments they want to pass when generating the bash completion script.

Adding per option arguments gets harder, you'll likely need to write a custom bash completion script.

**Comment by HuwCampbell** [comment]
Please reopen if you would like to chat about this more. Closing for now.
