### ISSUE TITLE
Composable nesting of subcommands

### ISSUE THREAD

**Issue by mightybyte** [pcapriotti/optparse-applicative#340]
I have a command line tool that wraps a bunch of subcommands, some of which are defined elsewhere.  This is causing problems because my top-level command's arguments are passed to the subcommands and cause them to fail.  Would it be possible to have a mechanism for removing the command line bits that the top-level optparse-applicative parser consumed so the subcommands don't see those and throw errors?

Right now my current workaround is to use `getArgs` and manually strip off the first element (the command) and then pass the rest of the list to the subcommands using `System.Environment.withArgs`.  If would be really nice if optparse-applicative could do this.

**Comment by HuwCampbell** [comment]
I'm really sorry, but I don't understand this issue at all. Could you please rephrase or give an example?
