### ISSUE TITLE
Prevent duplicate short flag names

### ISSUE THREAD

**Issue by domenkozar** [pcapriotti/optparse-applicative#346]
I've accidentally added `-h --host` while `-h --help` exists so it was shadowed. Maybe a generic test could help?

**Comment by HuwCampbell** [comment]
What sort of test do you suggest?

Optparse does support multiple options with the same name. They're just handled in sort order.

**Comment by HuwCampbell** [comment]
Going to close as I can't think of a way to action this. Feel free to follow up though.
