### ISSUE TITLE
Arguments not autocompleting 

### ISSUE THREAD

**Issue by buggymcbugfix** [pcapriotti/optparse-applicative#349]
I am parsing `many $ argument str $ metavar "GLOB_PATTERNS"` as arguments to my application, but these don't get autocompleted by my `fish` shell with the autocompletion given by `--fish-completion-script`. Removing the `--no-files` flag from the output seems to rectify this.

**Comment by HuwCampbell** [comment]
You haven't told the completer that it's supposed to work on files.
```haskell
many $ argument str $ metavar "GLOB_PATTERNS" <> action "file"
```
should do it.

**Comment by HuwCampbell** [comment]
The default completion action for options and argument strings is to do nothing, because we can't tell what action we're supposed to take or what you want to complete.

**Comment by buggymcbugfix** [comment]
Thank you. I missed this in the documentation.

**Comment by buggymcbugfix** [comment]
Alas, while this works for `bash`, it doesn't seem to work for `fish`. The output I get is exactly the same.

**Comment by HuwCampbell** [comment]
I can't reproduce. It's working for me.
