### ISSUE TITLE
Release version supporting GHC 8.8.1

### ISSUE THREAD

**Issue by asr** [pcapriotti/optparse-applicative#350]
GHC 8.8.1-alpha2 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2019-June/017777.html). I could compile the current master (83e096aa20cd4fd5328bf11c266115326d584e00) using this version of GHC. Could someone release a new version supporting GHC 8.8.1.

Blocking https://github.com/agda/agda/issues/3725.

**Comment by HuwCampbell** [comment]
I'm hoping to do a PR merge and do this this week.
