### ISSUE TITLE
Selective Applicative Functor Instance?

### ISSUE THREAD

**Issue by HuwCampbell** [pcapriotti/optparse-applicative#352]
Just a question at this stage.

What would adding a `Selective` instance do to the user interface? I actually hypothesise that we already sort of have one, and that the current commands interface is a selective applicative. So the current commands implementation could be rewritten to also support things like this:

```
Available commands:
  hello                    Selected with a positional token
  --this                   Selected with a flag
```

**Comment by HuwCampbell** [comment]
I have implemented this and it's underwhelming.

Given:
```haskell
data Value = B | C String
  deriving (Eq, Show)

a :: Parser String
a = strOption (short 'a')

b :: Parser Value
b = flag' B (short 'b')

c :: Parser (String -> Value)
c = flag' C (short 'c')

d :: Parser Value
d = ((Left <$> a) <|> (Right <$> b)) <*? c
```

We can expect this:
```bash
# Just to be clear, how this is rendered is just my current implemenation. It's hard to express clearly.
:main --help
Usage: <interactive> (-a ARG | -b) [-c]

:main -a ok
Missing: -c

:main -a ok -c
C "ok"

:main -b
B

:main -c
Missing: (-a ARG | -b)

:main -c -b
B
```

The first 3 cases make sense to me. The last two are problematic. Providing a `-c` yields a message saying I need an `a` or a `b`, but I won't be used by the `b` at all anyway. `-b -c` is exactly the same as `-b`.


I think most would use
```haskell
d :: Parser Value
d = a <**> c <|> b
```

**Comment by merijn** [comment]
Is the code of this selective attempt still somewhere? I think there's some nice use-cases for it and if I don't have to figure the implementation out myself, that saves a lot of time :)

**Comment by HuwCampbell** [comment]
https://github.com/pcapriotti/optparse-applicative/tree/expoloration/selective

**Comment by googleson78** [comment]
I've also been thinking about this, and it feels like having a selective interface makes perfect sense for subcommands. Did your original exploration try something like this?
