### ISSUE TITLE
Format sums without newlines

### ISSUE THREAD

**Issue by domenkozar** [pcapriotti/optparse-applicative#353]
```
Usage: cachix push [--compression-level [0..9]] NAME ([PATHS...] |
                   [-w|--watch-store])
```

This reads as if `-w` is a different command to `push` as it's easy to miss parenthesis. I don't have a clear suggestion but maybe sums shouldn't be broken into newlines.

**Comment by HuwCampbell** [comment]
Yes, I think
```
Usage: cachix push [--compression-level [0..9]] NAME
                                 ([PATHS...] | [-w|--watch-store])
```
would be nicer.

I think this is a great idea, and it should be possible with judicious use of Union, `flatten` and `group` in the pretty printer.

**Comment by HuwCampbell** [comment]
I believe I have a solution. Locally, I'm seeing this:
```
Usage: <interactive> push [--compression-level [0..9]] NAME 
                          [PATHS... | (-w|--watch-store)]
```

And to show it scales ok, I added some extra switches and flags...

```
Usage: <interactive> push [--compression-level [0..9]] NAME 
                          [PATHS... | (-w|--watch-store)] [-s] 
                          (--this-is-me | --this-is-you | --this-is-us) 
                          (--we-are-1 | --we-are-1 | --we-are-1 | --we-are-1 |
                          --we-are-1 | --but-we-all-can't-fit)
```

Essentially, alternatives will start a new line if they don't completely fit.
