### ISSUE TITLE
Command help should be flattened via `group` or provide some other interface for specifying alternates.

### ISSUE THREAD

**Issue by merijn** [pcapriotti/optparse-applicative#358]
I have subcommands that have pretty big help texts that I don't want reproduced in the subcommand listing of their parent command. Instead I'd like a short one line summary. There's two ways to accomplish this:

1) the subcommand help render could call `group` to flatten the `progDesc`, in this scenario I can simply use `flatAlt` to provide my one line summary for the command
2) add a new `InfoMod` function that explicitly specifies a short version to use in the command help (falling back to the regular version if no short version is specified)

I think option 2 is probably the best, since it won't suddenly change how anyone's help messages render, so it could be safely added as minor version bump. It should be comparatively simple to add these, so I can open a PR to fix this if the approach seems good.

As an added bonus this would also let me fix the cosmetic issue I complained about in #313.

**Comment by merijn** [comment]
@HuwCampbell ping?

**Comment by HuwCampbell** [comment]
Hi, sorry I think I wrote about half a response twice already for this.

So I don't think the first is really an option, it would be far too surprising and counter-intuitive.

With regards to 2, are you sure it's really necessary? I would hope that the header and footer docs could convey the information you're after without a change. Do you have an example that looks particularly bad?

I should look into #313. It's just cosmetic, but I'll have a look at a few parsers and see what I think.

**Comment by merijn** [comment]
> I would hope that the header and footer docs could convey the information you're after without a change. Do you have an example that looks particularly bad?

But the command summary doesn't user the header/footer, it uses progDesc, in my case several commands have a progDesc that is several paragraphs long. Having that inlined in the command summary is...fairly ugly to say the least.

Now, I suppose you could argue such long descriptions should go into the footer, but since I have quite a long list of subcommands/options I find it is much more readable to have it in between the usage.

> I should look into #313. It's just cosmetic, but I'll have a look at a few parsers and see what I think.

Now that I'm working on larger parsers I'm actually running into more tiny cosmetic warts (the most recent one that comes to mind is the fact that the "default" value gets attached to the help with a non-breaking space. So I've run into situations where a significant part of the help texts gets broken to the next line because the default won't fit, or (when I manually insert a break) the default starting on the next line prefixed by a space.

These aren't big problems, but `optparse-applicative` is so close to being perfect as an option parsing library that it just makes me sad I can't make it as perfect as it could be. That said, if you're open to minor cosmetic tweaking (i.e. doesn't change the API nor significantly change the way things are rendered) I can create PRs for these little things (but I prefer to not invest the time if you don't think these are worth changing).

As for #313, an example from my current parser would be:
```
Usage: Ingest [-d|--database DATABASE] [--vacuum-db]
              [(-q|--quiet) | (-v|--verbose N)] [--explain |
              --explain-log FILE] [--migrate] COMMAND
  Register GPUs, algorithms, algorithm implementations, and
  graphs in an SQLite database of configurations. Automatically
  run missing configurations and store all results in the
  database.
```
versus
```
Usage: Ingest [-d|--database DATABASE] [--vacuum-db]
              [(-q|--quiet) | (-v|--verbose N)] [--explain |
              --explain-log FILE] [--migrate] COMMAND

  Register GPUs, algorithms, algorithm implementations, and
  graphs in an SQLite database of configurations. Automatically
  run missing configurations and store all results in the
  database.
```

Where I (personally) find the latter much more readable. Having spent some time digging through the help rendering the past month or so, I think fixing #313 directly as a one-off is probably not worth it. I think there's more to be said for the solution I proposed here and/or expanding on `Options.Applicative.Help` to provide more control to users to structure how the help is rendered (but that's probably considerably more work which I don't have time for at the moment, so I haven't really looked into it/thought about how to do it yet).

**Comment by HuwCampbell** [comment]
> But the command summary doesn't use the header/footer, it uses progDesc, in my case several commands have a progDesc that is several paragraphs long. Having that inlined in the command summary is...fairly ugly to say the least.

Yes I understand, I was offering as a potential change that you could put more of that information into the header instead of the progDesc, which is usually for short snippets.

Another option is to traverse over the generated help with `overFailure` (in you case it would be more difficult than it should be though, as `infoProgDesc` is smooshed into the `helpUsage` field of the `ParserHelp` type, I'll make a note to separate these).

I don't think overall this is a bad idea, I'm just cautious of having too many ways of doing similar things.

**Comment by merijn** [comment]
> Another option is to traverse over the generated help with `overFailure` (in you case it would be more difficult than it should be though, as `infoProgDesc` is smooshed into the helpUsage field of the ParserHelp type, I'll make a note to separate these).

Yeah, this is something I already looked into, but I don't think the current `ParserHelp` is sufficiently granular to give fine-grained control over how the help gets rendered. Making that more fine-grained (I'd also been looking into whether it's possible to extract the flag/command sections from `ParserHelp`, but those also mostly got smooshed into other things.)

I can certainly try and make a branch that, instead of touching the `InfoMod` stuff, just makes `ParserHelp` more granular and provides more control over the rendering there.

**Comment by HuwCampbell** [comment]
I've made `ParserHelp` more granular now, so I'll close this one. Feel free to follow up.

**Comment by merijn** [comment]
Yeah, I think the current API covers all my needs (i.e. I can just handroll a custom pretty printer of ParserHelp and hook it into `execParserPure`), so I think this solves most/all of this issue.

**Comment by merijn** [comment]
Incidentally, did you have a plan/time frame for making a new Hackage release that includes this?

**Comment by HuwCampbell** [comment]
Yeah. I think I'll tackle the overflow issue haging about then put up a 0.17.

Maybe a week or two from now.
