### ISSUE TITLE
Can't hide a subcommand?

### ISSUE THREAD

**Issue by sjakobi** [pcapriotti/optparse-applicative#365]
At https://github.com/dhall-lang/dhall-haskell/compare/sjakobi/hide-parse-tree I try to add a hidden `parse-tree` subcommand.

The subcommand parser is essentially

```
hsubparser
    (   command "parse-tree" parserInfo
    <>  metavar "parse-tree"
    <>  hidden
    )
```

Yet the `hidden` modifier doesn't seem to have any effect. The command still appears in the "Available commands" list:

```
$ cabal run -- dhall:dhall -h
...
Available commands:
...
  parse-tree               Output the parsed syntax tree (for debugging)
```

 Am I doing something something wrong?

**Comment by HuwCampbell** [comment]
You want `internal` instead I believe.

`internal` hides from both the brief description as well as the long on. `hidden` only hides in the brief description.

**Comment by sjakobi** [comment]
Many thanks @HuwCampbell. I have opened #366 to improve the docs a bit.
