### ISSUE TITLE
Delegating completion and forward-options

### ISSUE THREAD

**Issue by cocreature** [pcapriotti/optparse-applicative#372]
Let’s say I have a`git`-style program `foo` which delegates to other programs based on the first command argument, e.g., `foo bar a b c` calls `foo-bar a b c`.  To implement this, I use `forwardOptions` and something like `many (strArgument …)`.

Now, I can figure out which executables exist and make sure that `foo ba` will complete to `foo bar`. However, after the command argument, I would like to delegate completion to the `foo-bar` executable.  I’m struggling to figure out how to implement this. The `Completer`  API requires me to operate on a single argument at a time so I cannot simply call `foo-bar` with all the arguments, e.g., `a b c` and let it do the completion. Is there a way of making this work?

Thanks for all your work on `optparse-applicative`!

**Comment by HuwCampbell** [comment]
So applicative style doesn't really lend itself well to inspection of the partially evaluated argument. You pretty need a monad for that.

But I have thought of a few things.

1) The first thing I would recommend is to change the autogenerated bash script to also call the completer for the sub programs which you're completing. This should be pretty simple and effective.

2) The next is to use getArgs or a separate optparse parser *inside* the completer itself. It's in IO, so this is very doable.

3) The last option is to not use `many` but instead look at how it's implemented on top of the internal `ParserM` monadic interface. You should be able to (it will work, but is hacky) build a custom `many_` which builds a completion action using the arguments already parsed.

**Comment by cocreature** [comment]
Thank you very much! I went for option 3 which is working great.
