### ISSUE TITLE
Overriding exit codes of various parse errors (especially help-on-empty)

### ISSUE THREAD

**Issue by moll** [pcapriotti/optparse-applicative#373]
Hey!

Thanks for maintaining Optparse! I'm trying to override the exit code of `prefShowHelpOnEmpty`. My reading of various Unix utilities is that the help text requests, including the empty invocation, exit with with a successful exit code. https://github.com/pcapriotti/optparse-applicative/issues/198 and its current state (https://github.com/pcapriotti/optparse-applicative/blob/master/src/Options/Applicative/Extra.hs#L157) both exit with failure. I'm not so much attempting to convince any maintainer to switch that to a successful exit as I am trying to get my own apps to exit successfully. :)

I thought the pure version of the parser would return sufficient information to do so, but its return values seem a little light on structured data, having already deconstructed that to error messages. 

1. What's the suggested method of achieving basically the same behavior as `prefShowHelpOnEmpty`, but a zero exit code?
2. What would the best method be to customize the exit codes for all other error messages individually? That is, something with more granularity than `infoFailureCode`.

Thanks!

**Comment by HuwCampbell** [comment]
Interesting point, maybe I should rethink the current behaviour there.

It's the `MissingError CmdStart _` that's important in this case. It should be pretty easy to write a custom `execParserPure` which behaves differently for `Left (MissingError CmdStart _)`.

On that case, abstract over the result from `parserFailure` to set the exit code to ExitSuccess instead.

**Comment by moll** [comment]
Hey again. Thanks! You're right, rewriting `execParserPure` doesn't seem too complicated, though it does go beyond the public API (due to [`runP`](http://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative-Internal.html#v:runP), I think).

I'm not yet sure where the optimal point of reuse for the future would lie. `parserFailure` seems to do quite a few [useful] things and splitting that up could probably help with customization. Maybe that would even permit removing some configuration if it's just as easy to change the exit code universally, for example, via wrapping the pure parser than it is today via the `failureCode` option. Same for adding text beyond the header-footer, formatting etc. Translation of error messages could be one thing that it may end up affording.

**Comment by HuwCampbell** [comment]
Interestingly, it looks like git acts like optparse here.

```bash
> git
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           ...
> echo $?
1
```

**Comment by HuwCampbell** [comment]
I don't think there's really much actionable here. I think what optparse is doing is the right thing, and it's consistent with git.
I'll close, but feel free to follow up.
