### ISSUE TITLE
Provide version of NonEmpty.some1 that has better help message defaults

### ISSUE THREAD

**Issue by 3noch** [pcapriotti/optparse-applicative#376]
Using `NonEmpty.some1` will duplicate help messages because it uses the applicative twice. This is usually easy to work around by building a parser directly with `liftA2 (NonEmpty.:|)` and removing help text from the second argument. However, it seems like this should be something that is more directly supported. It could possibly add `...` to the metavar as well to indicate "required" and "many".

**Comment by HuwCampbell** [comment]
I agree, this is not ideal. I could well add a custom `some1` specifically for optparse `Parser` using the same technique as our version of `some`.

I'm a little uncomfortable about name clobbering though.

Maybe I should call it `some1P` instead.

**Comment by 3noch** [comment]
Of course the name `some1` already seems to be a compromise for the sake of name-clashing since `some` should be sufficient to get you `NonEmpty`. I won't fight about the name, but just tossing `someNonEmpty` or similar into the ring instead of layering compromises.

**Comment by HuwCampbell** [comment]
Do you want to write it?

**Comment by 3noch** [comment]
I could take a stab but would appreciate a pointer or two where to start looking.

**Comment by HuwCampbell** [comment]
Look at the definition of `some` for parser in Types.hs.

**Comment by HuwCampbell** [comment]
#382

**Comment by 3noch** [comment]
Thank you!

**Comment by HuwCampbell** [comment]
This will be in the next release.
