### ISSUE TITLE
Feature Request: Namespace Command Shortcuts

### ISSUE THREAD

**Issue by razoyodev** [pcapriotti/optparse-applicative#377]
It would be really great if there was a built-in way to use namespace shortened commands like Symfony does (https://symfony.com/doc/current/components/console/usage.html). This way if we built out a tool with many commands, we would be able to have the ability to use abbreviations in the options without needing to manually build out each one.

**Comment by HuwCampbell** [comment]
Sorry I'm not familiar with that tool.

Could you please elaborate and give some examples.

**Comment by HuwCampbell** [comment]
Feel free to follow up, I'll close for now.
