### ISSUE TITLE
Expects an argument while there is an argument

### ISSUE THREAD

**Issue by NorfairKing** [pcapriotti/optparse-applicative#381]
I'm doing something with `optparse-applicative` and it doesn't seem to do what I want
```
many
      ( option
          (eitherReader (parseUsernameWithError . T.pack))
          (mconcat [long "admin", metavar "USERNAME", help "An admin"])
      )
```
This is what I to get a `[Username]`
but then when I pass `--admin admin` and expect to get `["admin"]`, I get (edited) 

```
The option `--admin` expects an argument.
```

am I doing something wrong?

**Comment by NorfairKing** [comment]
Using `Debug.Trace.traceShowId` I can see that the `eitherReader` is indeed called with `"admin"`..

**Comment by NorfairKing** [comment]
This was my mistake!:
I had `prefDisambiguate` set to `True`  and a new option that also started with `admin` somewhere else.

**Comment by HuwCampbell** [comment]
That is a strange error message. Can you share a snippet which reproduces it so I can have a look?

**Comment by NorfairKing** [comment]
@HuwCampbell I don't have a snippet, but it was happening because I had two things where one was a prefix of the other and one was an argument and the other an option.

Something like:
```
(,) <$> strArgument (long "foo") <*> strOption (long "foobar")
```
