### ISSUE TITLE
option to disable flag parsing

### ISSUE THREAD

**Issue by elaforge** [pcapriotti/optparse-applicative#388]
I have a command with a bunch of subcommands, some of which parse flags themselves, or pass them verbatim to another command.  In that case, I just want to collect the remaining arguments, regardless of whether they happen to start with `-` or not.

`noIntersperse` almost does this, but not quite, because it only turns off special treatment for `-` after a positional argument, so no good if the first argument happens to start with `-`.

Otherwise, I think my only workaround is to pre-parse the arguments before giving them to optparse, and if I see one of the special sub-commands, insert a `--` after it.

**Comment by HuwCampbell** [comment]
There's actually 4 run modes; I've builders for 2; and there's the default.

Read the docs [here](https://github.com/pcapriotti/optparse-applicative/blob/master/src/Options/Applicative/Types.hs#L373-L395).

Then have a look at how `noIntersperse` and `forwardOptions` are implemented.

**Comment by elaforge** [comment]
`AllPositionals` looks like the right thing, but since the constructor `InfoMod` isn't exported from `Options.Applicative.Builder` I don't think I can use it.  Shall I send a PR?

**Comment by HuwCampbell** [comment]
There's nothing stopping you from importing the `Types` module – all modules are under the PVP. I do strive a bit harder to make the builder APIs extremely stable. Regardless, if you're finding that functionality useful you can add a builder for it and put a PR up.

I am considering shifting this around a little bit; but again, that would be a major version bump.

I'll close this as I think it's answered, but feel free to follow up.

**Comment by elaforge** [comment]
The problem is here, I can't make my own `InfoMod`: https://github.com/pcapriotti/optparse-applicative/blob/master/src/Options/Applicative/Builder.hs#L67  

But it looks like I can directly construct a ParserInfo, so I can copy paste it out of `info` and set `infoPolicy`.  That also means I can't use any of the InfoMod stuff, so I also have to copy paste their definitions when needed.

I just tried it out, and all the copy-pasting is not ideal, but it does work.  I might still stick with the non-optparse pre-parse though, because while they're both a bit gross, the pre-parse is simple and clear.  How about export a builder for `AllPositionals` in the next major version?

**Comment by HuwCampbell** [comment]
Infomod with constructors is exported from `Options.Applicative.Types`, just import that and you'll be able to make your own builder.

**Comment by HuwCampbell** [comment]
Right. I see what you mean.

**Comment by HuwCampbell** [comment]
You should be able to just use record update syntax on your `ParserInfo` after it's constructed before running it.

`pinfo { infoPolicy = AllPositionals }`

**Comment by HuwCampbell** [comment]
And yes, I can include a new builder in the next version.

**Comment by elaforge** [comment]
Ok great, thanks a lot!
