### ISSUE TITLE
Please, provide the `--version` example in the documentation

### ISSUE THREAD

**Issue by Anton-Latukha** [pcapriotti/optparse-applicative#389]
Which we right-away encountered creating the project is: https://github.com/guibou/krank/issues/81

We both there just do not know how to process the `version`, nor I found a direct answer to that question during searches. It seems to be a basic case for any project, and since I looked at the couple projects - and they just choose to avoid to provide `--version` key.

So you are able to establish a proper practice just by one example.

It is also a great example to explain how library works. It explains how to get-in the `version` and return any information with some possibility to show how properly `--version` is done, so people would implement it in their projects.

Maybe replace some very basic example that repeats showing already shown things - with a `--version` one.

It is a great way to show how `external world -> program -> optparse-applicative -> IO` goes at once. It shows `--version`, establishes its proper practice, and does a round-rip of the data flow from IO to IO.

**Comment by ssanj** [comment]
I stumbled across this too. FP complete has an article that explains how to do it: https://tech.fpcomplete.com/haskell/library/optparse-applicative

And here is what I ended up doing: https://github.com/ssanj/pleat/blob/master/src/Commandline/CommandlineOptions.hs#L79

**Comment by HuwCampbell** [comment]
I'll try to find some time to add a page to the wiki.

For now:
The easiest way to add an option command is with `infoOption`, which is just a small composition over `abortOption`. The benefit of doing it this way is that it doesn't clutter up the cli with another alternative branch.

Some folks prefer to have an alternative case on the ADT for commands with is the Version command. In this case, I still recommend going down the route of having the type signature

```haskell
data Command
  = Base Some Things
  | Version

base :: Parser Command

version :: Parser (Command -> Command)
version = option id (const Version) (long "version" <> help "Display version" <> hidden)

opts :: ParserInfo Command
opts = info (base <**> helper <**> version) mempty
```

Although of course, it is possible to do it with an alternative as well.

To get the value of the version from Cabal, you'll need to import the generated `Paths_` module.

So you might end up with something like:
```haskell
import           Data.Version (showVersion)
import           Paths_your_package_name (version)

versioner :: Parser (a -> a)
versioner = infoOption (showVersion version) (long "version" <> help "Show version" <> hidden)

opts :: Parser Command
opts = info (base <**> helper <**> versioner) idm
```

```bash
> main --help
Usage: main COMMAND

Available options:
  -h,--help                Show this help text
  --version                Show version

> main --version
0.1.0.0
```

**Comment by Anton-Latukha** [comment]
As said, since currently one writing should figure this out by oneself, that there exists an ephemeral Cabal metadata submodule which can be imported and which holds a version variable which can be parser in this manner, it is good to include the last example into the documentation or at least into FAQ.

**Comment by HuwCampbell** [comment]
https://github.com/pcapriotti/optparse-applicative/wiki/Version-Options

**Comment by Anton-Latukha** [comment]
Thank you. Using the Wiki system for docs is a great thing.
