### ISSUE TITLE
Add `unswitch` function

### ISSUE THREAD

**Issue by vrom911** [pcapriotti/optparse-applicative#392]
`switch` is a quite useful function. However, sometimes you need an inverse function of it.

I propose to add `unswitch` function which is basically

```haskell
unswitch = flag True False
```

**Comment by HuwCampbell** [comment]
Hi Veronika,

That's an interesting one; it's pretty easy to roll this oneself as you've show, but also as `Parser` is a functor:
```
unswitch = fmap not . switch
```
I think maybe it's best to allow people to discover this themselves?

p.s.
Love your work.

**Comment by HuwCampbell** [comment]
I think I'm going to err on the side of a smaller API. Thanks for the suggestion though.

**Comment by vrom911** [comment]
@HuwCampbell fair enough.
Luckily writing it manually is not that hard, so I respect your decision :slightly_smiling_face: 

Thank you very much for your time!
