### ISSUE TITLE
Dynamic default value

### ISSUE THREAD

**Issue by yaitskov** [pcapriotti/optparse-applicative#393]
Hi,

there is a "value" function which supplies constant default value for an argument, but
it would be great to pass a function taking a context of all parameters.

```
   app input.file.xxx --output output.file.yyy
```

Let's say output is optional and by default should have same name with input.file but different extension.
If I pass Nothing to value then user should pass Just.

**Comment by yaitskov** [comment]
Workaround is to replace "optional auto" with

``` 
   <$> optional (strOption
```

**Comment by HuwCampbell** [comment]
Making the second argument optional looks very much the right thing to do here. You can map over the pair if needs be, or wait until the return from execution.

```
*Options.Applicative Data.Maybe> p = (\x y -> (x, fromMaybe x y)) <$> strArgument mempty <*> optional (strOption (long "output"))

*Options.Applicative Data.Maybe> execParserPure  defaultPrefs (info p mempty) ["this"] :: ParserResult (String, String)
Success ("this","this")

*Options.Applicative Data.Maybe> execParserPure  defaultPrefs (info p mempty) ["this", "--output", "that"] :: ParserResult (String, String)
Success ("this","that")
```

**Comment by HuwCampbell** [comment]
I don't think there's anything actionable here. Feel free to reach out though.
