### ISSUE TITLE
many and optional are indistinguishable in help

### ISSUE THREAD

**Issue by nomeata** [pcapriotti/optparse-applicative#394]
When wrapping an `option` in `many`, the help text encloses it with `[`…`]`
```
Usage: cmd [--foo STR]
```
which is indistinguishable from an optional field `--foo` (made optional either by wrapping in `optional`, or by passing `value`).

Is there a way to print either
```
Usage: cmd {--foo STR}
```
or
```
Usage: cmd [--foo STR ...]
```
or a similar form that makes the difference clearer?

**Comment by HuwCampbell** [comment]
There's some unreleased changes across many and optional when it comes to printing; also remember that `multiSuffix :: String -> PrefsMod` can gives a "...".

**Comment by HuwCampbell** [comment]
Here's my "extensive" test suite https://github.com/pcapriotti/optparse-applicative/blob/master/tests/test.hs#L780-L863 for this behaviour.

**Comment by nomeata** [comment]
Thanks! Looking forward to these changes :-)

**Comment by HuwCampbell** [comment]
`multiSuffix` has been around a long time; for the rest I'm planning on doing a release quite soon.
