### ISSUE TITLE
Make ReadM fail based on previous parsed value

### ISSUE THREAD

**Issue by soywod** [pcapriotti/optparse-applicative#401]
I have a basic command `add` that takes 2 kind of arguments: a word or a tag. A tag is just a word starting by `+`. A word is just a `String`. It can contain at least one argument (I use `some` for this).

```haskell
addCommand :: Mod CommandFields Arg
addCommand = command "add" (info parser infoMod)
  where
    infoMod = progDesc "Add a new task"
    parser = Add <$> parseDescAndTags <$> partition isTag <$> some (argument str (metavar "DESC"))
    parseDescAndTags (_, []) = FAIL HERE
    parseDescAndTags (tags, desc) = AddOpts (unwords desc) (map tail tags)
```

I want to add another rule: the `add` command should receive at least one word (but 0 or more tags). For this, I need to check after the first parsing the word list. If it's empty, I would like to fail as if the `add` commands received no argument, but I can't figure out how to do. The doc explains how to fail inside the ReadM but not outside:

> One can also use ReadM directly, using readerAsk to obtain the command line string, and readerAbort or readerError within the ReadM monad to exit with an error message.

It could be interesting to add more example about this.

Thank you for your help,

**Comment by HuwCampbell** [comment]
I don't exactly follow sorry, the code you've written isn't really valid as `fmap` can't be chained in that way.

I would probably put the tags under an option, with `short 't' <> long "tag"`, so the user would write something like:

```
add word1 word2 --tag tag1 -t tag2
```

Then the parser would be
```
Add <$> some (strArgument (metavar "WORD")) <*> many (strOption (short 't' <> long "tag" metavar "TAG"))
```
or something along those lines,.

**Comment by soywod** [comment]
Thank for your reply.

> I don't exactly follow sorry, the code you've written isn't really valid as fmap can't be chained in that way.

Sorry I'm still new to Haskell, someone proposed this version on [stackoverflow](https://stackoverflow.com/questions/63177527/optparse-applicative-consecutive-parsing-readm) (which make more sense): 

```haskell
Add . parseDescAndTags . partition isTag <$> some (argument str (metavar "DESC"))
```

What I try to achieve is to be able to write this kind of input: `add my awesome +v1 tool +v2`, and get this output: `tags: [v1, v2], desc: "my awesome tool"`, but as mentioned in the stackoverflow reply it seems not possible due to the nature of the lib itself (could you confirm?).

I tried also another alternative: to place all tags first, then the desc:

```haskell
addCommand :: Mod CommandFields Arg
addCommand = command "add" (info parser infoMod)
  where
    infoMod = progDesc "Add a new task"
    tagsParser = many (argument tag (metavar "TAG"))
    descParser = unwords <$> some (argument nonTag (metavar "DESC"))
    opts = AddOpts <$> tagsParser <*> descParser
    parser = Add <$> opts
```

But when I write `add +tag desc` I get a `desc can't be parsed`. I guess it's considered as a tag an fail.

Thank you for your help,

**Comment by HuwCampbell** [comment]
The response you received on SO looks reasonable. In essence, the API you're after can't be expressed without a monad instance, and by design we don't support one, as it would make things like rendering the help text impossible (how would you render the usage line of the UI you've proposed?).

I would still suggest using options for tags, but a second pass validation as was suggested could work for you too.

**Comment by soywod** [comment]
I finally chose the simplest way as suggested (basic options like `--tag`, `--project`, `--due`). For those who are looking for the same kind of question, [here the result](https://github.com/soywod/unfog/blob/master/src/ArgParser.hs). Thanks for your help!

PS: Your lib is awesome, it was really a pleasure to integrate. I'm still new to Haskell, but once I reach a good level I would love to contribute!
