### ISSUE TITLE
Require at least one of two options

### ISSUE THREAD

**Issue by zliu41** [pcapriotti/optparse-applicative#404]
In my use case I have options `--foo` and `--bar`. They both have default values but I need the user to specify a value for at least one of them.

According to #333, there's no backtracking, so using `<|>` to combine two parsers, one requiring `--foo` and the other requiring `--bar` won't work.

Is adding a separate check outside the parser the only way?

**Comment by HuwCampbell** [comment]
Are you trying to parse a [`Data.These`](http://hackage.haskell.org/package/these-1.1.1.1/docs/Data-These.html#t:These).

**Comment by zliu41** [comment]
Yeah I'm basically trying to parse a `These String String`, but prefer using two options `--foo` and `--bar` for the left and right value, rather than a single option.

**Comment by HuwCampbell** [comment]
Ok. This is unfortunately a little tricky.

Although `These` is a normal algebraic data type, not having backtracking means it's not possible to write with optparse's standard applicative API if you just want to flag names. So in general, I would suggest doing a post validation step.

But no, it's not _the only way_. It is possible using the internal (unsupported, but quite stable) monadic API which is used mostly for `many` and `some`. Doing this is may not be the best idea however, as it breaks multi-suffix printing, and can't be rendered meaningfully by the help text generator.

```haskell
import Data.These
import Options.Applicative
import Options.Applicative.Types

-- Whatever these are
a :: Parser A
b :: Parser B

ab :: Parser (These A B)
ab = fromM (oneM a >>= \a' -> maybe (This a') (These a') <$> oneM (optional b))
 <|> fromM (oneM b >>= \b' -> maybe (That b') (flip These b') <$> oneM (optional a))
```

**Comment by zliu41** [comment]
Thanks for the explanation!
