### ISSUE TITLE
Support some concept of localization for default texts

### ISSUE THREAD

**Issue by cohomology** [pcapriotti/optparse-applicative#405]
At the moment, several default texts are used in english language, i.e. "Show this help text" or "Usage". Optimally there should be some kind of l10n-concept applied, where the user can turn on that the texts appear in some foreign language. Is this already possible somehow?

**Comment by HuwCampbell** [comment]
Great question, but unfortunately no, at this stage we don't really have any localisation support.

It's been on my radar for quite a while now, so probably worth addressing it.

**Comment by cohomology** [comment]
In my app, I localized all texts in two languages only and map all other languages to english, like so:

[hlabyrinth](https://github.com/cohomology/hlabyrinth/blob/master/src/Main.hs)

So automatic localization would be bad. I guess the language should be passed from the user, otherwise you can get language mixture again ...

**Comment by HuwCampbell** [comment]
Closing as a duplicate of #9
