### ISSUE TITLE
Ugly help text formatting with long field names 

### ISSUE THREAD

**Issue by georgefst** [pcapriotti/optparse-applicative#406]
As far as I can tell, there's no way to set the width for the first column in the help text? This seems to correspond to the hard-coded `24` in `Options.Applicative.Help.Chunk`.

**Comment by HuwCampbell** [comment]
Duplicate of #258, but I completely agree. I should have fixed this for the 0.16 release – don't think I can get away with a minor version bump on this one.

**Comment by georgefst** [comment]
Aha, I did do a quick search but missed that issue. The second option discussed there would indeed be cool, but I'd be more than happy if it were just manually configurable.

**Comment by HuwCampbell** [comment]
Yeah, unfortunately I think you'd have to run the rendering algorithm twice to build it, which wouldn't be good at all.

I've got a PR up #407 to address this.

**Comment by georgefst** [comment]
Thanks @HuwCampbell - impressively quick!
