### ISSUE TITLE
Bash completion does not support output redirection

### ISSUE THREAD

**Issue by mklinik** [pcapriotti/optparse-applicative#411]
Hi,

First of all, this library is amazing. Especially the bash completion feature. This feature alone made me switch to optparse-applicative.

However, there is no filename completion for output redirection. Let's say my program is called `foo`. The default completion that comes with bash for unknown programs lets you complete filenames like this:

```
$ foo > /home/<TAB>
```

When the completion script generated by optparse-applicative is sourced, this no longer works.

```
$ source <(foo --bash-completion-script `which foo`)
$ foo > /home/<TAB>
```

Would it be hard to support this?

**Comment by HuwCampbell** [comment]
I'll look into this.

**Comment by HuwCampbell** [comment]
And thanks for the kind words :)

**Comment by HuwCampbell** [comment]
So as I kind of suspected, the `>` is passed directly through the completion script, so for a simple program we'll receive something like this:

```
--bash-completion-index 3 --bash-completion-word git --bash-completion-word log --bash-completion-word '>' --bash-completion-word -
```

I'll have a look at how we might do this better. I expect it will be subtle.

**Comment by HuwCampbell** [comment]
Looks like zsh just does the right thing already.

**Comment by HuwCampbell** [comment]
Can you find an example of a bash completion script which does this correctly?

**Comment by mklinik** [comment]
I would consider this a bug in bash. The shell should not pass this `>` to the completion script. If you use `&>` for redirection, bash recognizes this symbol and performs auto-completion itself, but apparently not for any other redirection syntax like `1>`, `2>` etc.

Let's consider this issue as a wontfix.

**Comment by HuwCampbell** [comment]
I'm inclined to agree.

I was actually thinking the title of this issue is an accurate statement about bash rather than an issue in optparse-applicative.
