### ISSUE TITLE
Metavars formatted with ANSI sequences have messed up alignment in --help

### ISSUE THREAD

**Issue by mitchellwrosen** [pcapriotti/optparse-applicative#412]
Here's an example.

Without cyan coloring:

<img width="1778" alt="Screen Shot 2021-01-04 at 11 26 05 AM" src="https://user-images.githubusercontent.com/1074598/103556421-c05c0000-4e7f-11eb-82ef-8cd77ed61a44.png">

With cyan coloring:

<img width="1778" alt="Screen Shot 2021-01-04 at 11 25 53 AM" src="https://user-images.githubusercontent.com/1074598/103556451-cce05880-4e7f-11eb-8540-60209b1d603c.png">

**Comment by HuwCampbell** [comment]
Try `metavar "abc" <> style Text.PrettyPrint.ANSI.Leijen.cyan` instead.

**Comment by HuwCampbell** [comment]
Thinking about it it, I could well change the type of `propMetavar` to `Chunk Doc` instead of string and provide a `metavarDoc` builder as well.

**Comment by mitchellwrosen** [comment]
Ah, great, thanks!

**Comment by HuwCampbell** [comment]
I'll close this, but feel free to follow up.
