### ISSUE TITLE
Dependent completions

### ISSUE THREAD

**Issue by samhh** [pcapriotti/optparse-applicative#424]
I have a `Parser` which has two consecutive arguments, the second of which's completions depends upon the first.

Here's what I mean, where the `x` in the second argument should be the value from the first argument (passed in like this or in the completion function argument is irrelevant).

```hs
fstCompleter :: A.Completer
sndCompleter :: Text -> A.Completer

p :: A.Parser (Text, Text)
p = (,)
  <$> A.argument A.str (A.completer fstCompleter)
  <*> A.argument A.str (A.completer (sndCompleter x))
```

I can't work out a simple solution as these constructs aren't monadic. What are my alternatives? (Assuming I'm not missing something obvious!)

Possibly related: #372

**Comment by HuwCampbell** [comment]
> Possibly related: #372

Very much so.

There's no general way to do this, as you would need a monad instance to get the dependency coming from one argument to the other; and a Monadic parser means we can't generate traverse to build a help text, or easily permute the order of arguments.

Getting this right with the internal `ParserM` api is probably possible, but very finnicky.

**Comment by HuwCampbell** [comment]
I'm going to close this as I don't think there's anything I can action here. Feel free to follow up.

**Comment by hasufell** [comment]
I'm currently looking into having a url-completer. So the completer would basically fetch the current files/dirs from the remote, then call itself, until the user presses enter.

Does this also fall short due to the described limitation?

**Comment by HuwCampbell** [comment]
Not sure without extra context. Feel free to open a separate issue to discuss what you want more precisely or point me to a branch (is this for ghcup?).
