### ISSUE TITLE
Compatibility with transformers 0.6

### ISSUE THREAD

**Issue by sjakobi** [pcapriotti/optparse-applicative#427]
https://hackage.haskell.org/package/transformers-0.6.0.0/changelog

Could you upload a compatible release or make a Hackage revision?

Note that https://github.com/ekmett/transformers-compat/issues/48 will probably need to be addressed first.

**Comment by HuwCampbell** [comment]
Thanks for the heads up.

I've been thinking I might reänalyse our dependency on transformers-compat anyway. I'll see what I can do.

**Comment by HuwCampbell** [comment]
I tried to do get a build without transformer-compat, but GHC 7.8 couldn't find an install plan. So it looks like we may have to wait for the issue above. 

When it's done and after I've tested I'll do a hackage revision.

**Comment by sjakobi** [comment]
> I tried to do get a build without transformer-compat, but GHC 7.8 couldn't find an install plan.

Several core packages are cutting support for GHC < 8. For example:

* `bytestring` [will do so](https://github.com/haskell/bytestring/pull/265) in the next major release (v0.12). 
* `random` already requires GHC >= 7.10
* `text` will also do so in the next major release: https://github.com/haskell/text/pull/336

IMHO you could do the same, but it's up to you of course.

**Comment by HuwCampbell** [comment]
We could, but I quite like that we can offer such a wide range.

Haskell 98 is a really solid language and IMO it's important to keep things nice and steady in a project like this one.

Fix is on master, I'll put up a branch off of the last tagged release for CI to do a final check on then do a hackage update as well.

**Comment by HuwCampbell** [comment]
Hackage revision is done for 0.16.1 as well.
