### ISSUE TITLE
Is it possible to have some non-permutation parsing?

### ISSUE THREAD

**Issue by newhoggy** [pcapriotti/optparse-applicative#432]
Sometimes it is useful to parse the command line in a non-permuting way.  For in the following example the `--tx-out-datum-hash y` is parsed in such a way as to end up being a child of the last `TxOut`.

```
$ optparse-applicative-demo demo --tx-out 1 --tx-out 2 --tx-in x --tx-out-datum-hash y --tx-out 3
DemoOptions {txouts = [Right (TxOut {txOut = "1", txOutDatumHash = Nothing}),Right (TxOut {txOut = "2", txOutDatumHash = Nothing}),Left (TxIn {txIn = "x"}),Right (TxOut {txOut = "3", txOutDatumHash = Just "y"})]}
```

When the `--tx-in x` is removed however, the `--tx-out-datum-hash y` is reassociated with the second last `TxOut` instead.

```
$ optparse-applicative-demo demo --tx-out 1 --tx-out 2  --tx-out-datum-hash y --tx-out 3
DemoOptions {txouts = [Right (TxOut {txOut = "1", txOutDatumHash = Nothing}),Right (TxOut {txOut = "2", txOutDatumHash = Just "y"}),Right (TxOut {txOut = "3", txOutDatumHash = Nothing})]}
```

This is despite the relative order of all the arguments remaining unchanged.

The sort of feature I'm interested in is if permutation parsing can be disabled for some sub-parsers to eliminate some unintuitive behaviour.

**Comment by newhoggy** [comment]
I've attached the project that produces the above behaviour.

[optparse-applicative-demo.tar.gz](https://github.com/pcapriotti/optparse-applicative/files/6898103/optparse-applicative-demo.tar.gz)

**Comment by HuwCampbell** [comment]
At first blush, one would usually use arguments for non-permuting things; for completeness though, you could use the internal ParserM api to do this as well.

**Comment by HuwCampbell** [comment]
I'm going to close this as I don't think there's anything actionable. You can use the ParserM monad if you want, but I would suggest using arguments.
