### ISSUE TITLE
Mixing global and local arguments to subparser

### ISSUE THREAD

**Issue by simonmar** [pcapriotti/optparse-applicative#433]
```
import Options.Applicative

data Options = Options
  { global :: Bool
  , cmd :: Bool
  }
  deriving Show

opts :: Parser Options
opts =
  Options
    <$> switch (long "global")
    <*> subparser (command "command" (info (switch (long "local")) fullDesc))

main = print =<< execParser (info (opts <**> helper) fullDesc)
```

```
Main> :main command
Options {globalFlag = False, cmd = False}
*Main> :main command --local
Options {globalFlag = False, cmd = True}
*Main> :main command --local --global
Options {globalFlag = True, cmd = True}
*Main> :main command --global --local
Invalid option `--local'

Usage: <interactive> [--global] COMMAND
*** Exception: ExitFailure 1
```

I've seen this trip people up a lot, and it's a pain having to explain how you can't intersperse the global and local options. Is there some reason the parser can't let you arbitrarily permute global and local options after the command?

**Comment by HuwCampbell** [comment]
Hi Simon. Yes, this one can be a pain.

What you're looking for is the `subparserInline` modifier.

For backwards compatibility reasons its not the default unfortunately, but it changes the way subparsers are run by substituting them into the top level instead of running them individually when they're reached.

```haskell
main :: IO ()
main = print =<< customExecParser (prefs subparserInline) (info (opts <**> helper) fullDesc)
```

```
*Options.Applicative> :main command
Options {global = False, cmd = False}
*Options.Applicative> :main command --local
Options {global = False, cmd = True}
*Options.Applicative> :main command --local --global
Options {global = True, cmd = True}
*Options.Applicative> :main command --global --local
Options {global = True, cmd = True}
```

**Comment by simonmar** [comment]
Oh wow, I should have found that. Thanks!

Maybe it would be easier to find if there was a note in the docs for `subparser` and `hsubsparser`?

**Comment by HuwCampbell** [comment]
No problem, and that's a good idea.

**Comment by HuwCampbell** [comment]
I've just pushed https://github.com/pcapriotti/optparse-applicative/commit/4a20540894ffe8922c40287bfc304ef89fe5c67f to master, which should help in future.
