### ISSUE TITLE
brief description displays `infoOption`s conjunctively rather than disjunctively

### ISSUE THREAD

**Issue by andreasabel** [pcapriotti/optparse-applicative#437]
Info options are by nature disjunctive, so you cannot supply them together with other options.  However, the auto-generated brief description suggests otherwise:

Output of help:
```
Usage: foo-bar [--delete] [-v|--verbose] [--version]

Available options:
  --delete                 Actually clean up on disk.
  -v,--verbose             Comment on what is happening.
  --version                Show version info.
  -h,--help                Show this help text
```
This suggests `--version` is an option to modify the operational behavior of `foo-bar` (like `--delete`), rather than what it is: a completely separate mode of operation.

Source code:
```haskell
options = execParser $ info parser infoMod
  where
  parser  = programOptions <**> (versionOption <*> helper)

  versionOption =
    infoOption "FOO"
      $  long "version"
      <> help "Show version info."
...
```

Correct (and desirable) would be the following output:
```
Usage: foo-bar [--delete] [-v|--verbose] 
       foo-bar --version
...
```

Version: `optparse-applicative-0.16.1.0`

**Comment by HuwCampbell** [comment]
I've written up a little piece on version options.

https://github.com/pcapriotti/optparse-applicative/wiki/Version-Options

In essence you're free to use an alternative if you want to. Personally I find

```
foo-bar ([--delete] [-v|--verbose]) |  --version
```

a bit heavy. Also means one can't just chuck a `--version` in anywhere and have it work.

**Comment by andreasabel** [comment]
Thanks for the pointer.
In your wiki article, an alternative `Version` in the `Command` type is required.
However, since `infoOption` is "a parser that always fails" and just outputs a message, would it make sense that I do not need to declare an alternative (which is anyway never chosen since the parser fails)---so I could get the same convenience as with `infoOption`.

In the line with the OP, note that the current conjunctive handling of `infoOption` does not match the mathematical expectation.  If the `infoOption` parses the empty type (`0`) since the parser fails, disjunctively you get `A + 0 = A`, so you can add the empty alternative without losing your other options `A`, but `A * 0 = 0`...
