### ISSUE TITLE
Release 0.17?

### ISSUE THREAD

**Issue by brandonchinn178** [pcapriotti/optparse-applicative#443]
It seems like the last release was over a year ago. Any estimate on when the next version will be released?

**Comment by HuwCampbell** [comment]
Yes this is definitely something I want to do soon.

**Comment by moll** [comment]
Hey, I second that. :) I wanted to use `helperWith`, but noticed that was added after last year's v1.16.1 release.

**Comment by HuwCampbell** [comment]
Done

**Comment by moll** [comment]
Thank you!
