### ISSUE TITLE
Documentation referring to "show globals" default value is incorrect

### ISSUE THREAD

**Issue by moll** [pcapriotti/optparse-applicative#444]
Hey,

https://github.com/pcapriotti/optparse-applicative/blob/29c6dad223e29faf3ca66e4af7b1311bd212dfbf/src/Options/Applicative/Types.hs#L126-L128 describes globals as being shown by default, but I believe that they're actually off by default — at least looking at `defaultPrefs`.

Cheers

**Comment by HuwCampbell** [comment]
Ta. Fixed in #445
