### ISSUE TITLE
optparse-applicative-0.17.0.0 probably broke criterion

### ISSUE THREAD

**Issue by Mikolaj** [pcapriotti/optparse-applicative#446]
Just reporting for confirmation, so that we can ask whomever needs to fix that (e.g., criterion maintainer or Hackage trustees?). Here's the log:

https://github.com/Mikolaj/horde-ad/runs/5019750459

**Comment by Mikolaj** [comment]
Pinging @bos and @RyanGlScott.

**Comment by RyanGlScott** [comment]
`criterion` maintainer here. I'll apply Hackage revisions to affected versions soon, as well as upload a new Hackage version which properly supports `optparse-applicative-0.17.*`. I'll track these efforts on haskell/criterion#258.

**Comment by Mikolaj** [comment]
@RyanGlScott: thank you very much, buddy. Closing.

**Comment by HuwCampbell** [comment]
Dang, I do try to keep breaking changes minimal. My, apologies, I'm glad it was sorted out quickly.

**Comment by Mikolaj** [comment]
@HuwCampbell: you did PVP right, no need to apologise. Thank you very much for your maintainership!
