### ISSUE TITLE
URL completer?

### ISSUE THREAD

**Issue by hasufell** [pcapriotti/optparse-applicative#448]
ghcup allows to install artifacts from arbitrary URLs, e.g.:

```sh
ghcup install ghc -u https://downloads.haskell.org/~ghc/9.2.1/ghc-9.2.1-x86_64-alpine3.12-linux-gmp.tar.xz 9.2.1-gmp
```

My idea was to have a url completer that:

1. once you input `-u` it will return a static list of interesting URLs for completion, e.g. `https://downloads.haskell.org/~ghc/`
2. the user accepts the completion
3. the next completion now would use `listIOCompleter`, download the list of files directories from `https://downloads.haskell.org/~ghc/` and serve them as the next completion
4. repeat 3. until an item that doesn't end with `/` is accepted

I'm not sure if this can be realized with optparse-applicative, having multiple completion-steps for a single argument.

The optparse code is [here](https://gitlab.haskell.org/haskell/ghcup-hs/-/blob/8afabf3ffb4eccee2809e7cb8a7fe1daec9b473a/app/ghcup/GHCup/OptParse/Install.hs#L186-193) and the type is [`URI`](https://hackage.haskell.org/package/uri-bytestring-0.3.3.1/docs/URI-ByteString.html#v:URI).

**Comment by hasufell** [comment]
The documentation is rather lacking... I'm not even sure what the first argument `String` here is:

https://github.com/pcapriotti/optparse-applicative/blob/d307e46e3b233a395989dc3c3ed2299fcf5963a6/src/Options/Applicative/Types.hs#L313-L315

**Comment by hasufell** [comment]
After playing around with it, I don't think it's possible to do what I described.

Once you select a completion, the completion is done, it doesn't recurse, so you only ever have *one* completion step for a given completion.

**Comment by hasufell** [comment]
Ah, I forget to prepend the word to the next result... that messed up the second+ completion.

**Comment by hasufell** [comment]
Here's my take: https://gitlab.haskell.org/haskell/ghcup-hs/-/blob/c692a40c5766d803c23aff0625702e7fd0c50a26/app/ghcup/GHCup/OptParse/Common.hs#L455-564

**Comment by HuwCampbell** [comment]
I'll update the documentation for mkCompleter, but it looks like you've figured it out.
