### ISSUE TITLE
Listification (like `some1`) does not change the `metavar` to plural

### ISSUE THREAD

**Issue by andreasabel** [pcapriotti/optparse-applicative#451]
E.g. `some1` does not seem to have any effect on the help text:
```haskell
...
  oInputs :: Parser (List1 FilePath)
  oInputs = some1 $
    strArgument
      $  metavar "FILE"
      <> action "file"
      <> help "File to check"
```
The produced help text is:
```
Usage: ... [--version] [--numeric-version] FILE
```
This suggests _exactly one_ file when the semantics is _at least one_ file.

The long help text also does not give any clues:
```
Available options:
  -h,--help                Show this help text
  --version                Show version info.
  --numeric-version        Show just version number.
  FILE                     File to check
```

Version: `optparse-applicative-0.17.0.0`

**Comment by HuwCampbell** [comment]
The `[multiSuffix](https://hackage.haskell.org/package/optparse-applicative-0.17.0.0/docs/Options-Applicative-Builder.html#v:multiSuffix)` option is what you're after here.

A usual argument is `...`.

If hindsight was 20 / 20 I think this would have a better default.

I'll close this issue for now, but feel free to follow up.

**Comment by andreasabel** [comment]
Excellent, thanks for the swift advice!
