### ISSUE TITLE
Add ability to group aliases in --help

### ISSUE THREAD

**Issue by chshersh** [pcapriotti/optparse-applicative#453]
I would like to provide several aliases for the same option.

For example, American and British options and different combinations of prefixes:

+ **Group 1:** `--colour`, `--color`, `--enable-colour`, `--enable-color`
+ **Group 2:** `--no-colour`, `--no-color`, `--disable-colour`, `--disable-color`

I would like to display only the first option from each group in the `--help` text (or at least the ability to group help text for all options). 

This is helpful for providing multiple aliases for the same command. People might not remember the exact naming convention for this particular tool so supporting several standard options provides better UX.

Currently available solution is to duplicate the option name several times. However, this results in unnecessary output, even when using the `hidden` function:

```
Colouring example

Usage: script [--colour | --color | --enable-colour | --enable-color | 
                --no-colour | --no-color | --disable-colour | --disable-color]

  Example of verbose output

Available options:
  -h,--help                Show this help text
  --colour                 Enable colour
  --color                  Enable colour
  --enable-colour          Enable colour
  --enable-color           Enable colour
  --no-colour              Disable colour
  --no-color               Disable colour
  --disable-colour         Disable colour
  --disable-color          Disable colour
```

So, unfortunately, there's no way to group semantically the same options in the `--help` text.

<details>
  <summary>Complete Haskell example</summary>
  
```haskell
#!/usr/bin/env cabal
{- cabal:
build-depends:
  , base ^>= 4.14.1.0
  , optparse-applicative ^>= 0.17
-}

import Control.Applicative (Alternative (..))

import qualified Options.Applicative as Opt

colourParserInfo :: Opt.ParserInfo Bool
colourParserInfo = Opt.info (Opt.helper <*> colourP) $ mconcat
    [ Opt.fullDesc
    , Opt.header "Colouring example"
    , Opt.progDesc "Example of verbose output"
    ]

colourP :: Opt.Parser Bool
colourP = enableColour <|> disableColour <|> pure True
  where
    enableColour :: Opt.Parser Bool
    enableColour =
            mkEnableFlag "colour"
        <|> mkEnableFlag "color"
        <|> mkEnableFlag "enable-colour"
        <|> mkEnableFlag "enable-color"

    disableColour :: Opt.Parser Bool
    disableColour =
            mkDisableFlag "no-colour"
        <|> mkDisableFlag "no-color"
        <|> mkDisableFlag "disable-colour"
        <|> mkDisableFlag "disable-color"

    mkEnableFlag name  = mkFlag True  name "Enable colour"
    mkDisableFlag name = mkFlag False name "Disable colour"

    mkFlag val name helpText = Opt.flag' val $ mconcat
        [ Opt.long name
        , Opt.help helpText
        , Opt.hidden
        ]

main :: IO ()
main = Opt.execParser colourParserInfo >>= print
```
</details>

**Comment by HuwCampbell** [comment]
You can use `internal` to really really hide options. Is there anything else you would like to show?

**Comment by chshersh** [comment]
@HuwCampbell That works for me! Missed `internal` from API 😅 
Thanks a lot! 🙏🏻
