### ISSUE TITLE
Offer a positional parser

### ISSUE THREAD

**Issue by phderome** [pcapriotti/optparse-applicative#457]
Do you see any value in something like the below? User can then choose whether the tokens seen on the line can fit a particular data requirement or simply convert `[a]` to `Text`.

Is there something equivalent that exists that I missed? If this is of interest, it could be shown as a very trivial no-op example in README.

```
positionalParser :: IsString a => Parser [a]
positionalParser = some $ argument str mempty
```

**Comment by HuwCampbell** [comment]
Sorry I'm not sure I understand the question.

Applying `some` oneself is a common idiom, and helps build an understanding of the `Alternative` class. The read me also does contain this already [here](https://github.com/pcapriotti/optparse-applicative#arguments).

**Comment by phderome** [comment]
> Sorry I'm not sure I understand the question.
> 
> Applying `some` oneself is a common idiom, and helps build an understanding of the `Alternative` class. The read me also does contain this already [here](https://github.com/pcapriotti/optparse-applicative#arguments).

I must have missed the entry in the README you pointed. Thanks for your answer.
