### ISSUE TITLE
Parse in interactive program

### ISSUE THREAD

**Issue by reixn** [pcapriotti/optparse-applicative#458]
Is it possible to use optparse-applicative to parse commands and provide completion in an interactive cli program (e.g. use with haskeline)?

**Comment by HuwCampbell** [comment]
I think this question has been asked before, but yes, reüsing the completion system for haskeline is quite doable.

I don't have an example on hand, but essentially it's taking the haskeline input and passing it to the parser under the completion monad. You'll need to reverse it an split in into words appropriately (respecting quotes for example), then:

```haskell
runCompletion (runParserInfo pinfo words) pprefs
```

is the idea. That should give you either some `Parser` or an IO action to run for contextual ones (like a bash invocation to list directories).

Look at `BashCompletion.hs` for how we turn these into command line completions, you'll just need to wrap everthing up into Haskeline `Completion`s instead.

**Comment by HuwCampbell** [comment]
Best of luck
