### ISSUE TITLE
Export `requote` from `Options.Applicative.Builder.Completer`

### ISSUE THREAD

**Issue by janmasrovira** [pcapriotti/optparse-applicative#459]
The function `bashCompleter` currently only allows the user to pass an action argument.
If you want something fancier, e.g., complete with all files with a certain extension plus directories, you need to define a `Completer` from scratch. It could look like this:

```
extCompleter :: Completer
extCompleter = Completer $ \word -> do
  let cmd = unwords ["compgen", "-o", "plusdirs", "-f", "-X", "!*.ext", "--", requote word]
 ...
```
And it would be very convenient if we could import the helper function `requote` from the library instead of copy and pasting to our project.

**Comment by HuwCampbell** [comment]
https://github.com/pcapriotti/optparse-applicative/pull/460

**Comment by HuwCampbell** [comment]
Done
