### ISSUE TITLE
Apply style for command groups

### ISSUE THREAD

**Issue by ad-si** [pcapriotti/optparse-applicative#485]
Following code compiles, but it doesn't work:

```hs
subparser
    (  metavar "Basic Commands"
    <> (commandGroup "Basic Commands:" <> style brackets)
    <>  …
```

[The documentation](https://hackage.haskell.org/package/optparse-applicative-0.18.1.0/docs/Options-Applicative.html#v:style) says "option description" , but since it compiles, shouldn't it also work?

**Comment by HuwCampbell** [comment]
The parentheses aren't really doing what you're trying to make them do. Remember that the monoid laws include associativity – putting the parens there doesn't do anything.

The metavar (also 'Basic Commands') is getting brackets, which is the part of the help text that style has an impact on.

With the style modifier:
<img width="483" alt="image" src="https://github.com/pcapriotti/optparse-applicative/assets/5205457/48b13969-02b2-4b77-9083-061727fecab3">

Without:
<img width="488" alt="image" src="https://github.com/pcapriotti/optparse-applicative/assets/5205457/54eef2da-2568-4dcf-bc43-5394d1ebba62">

**Comment by ad-si** [comment]
Wow, thanks for the clarification! Another point on my list "why I don't like applicative interfaces" 🙈😅

Can we then maybe add a `commandGroupDoc` function?

**Comment by HuwCampbell** [comment]
That might work but it would not work too well with the way command groups do extra grouping by equality of names.

But maybe that was a bad API choice.

I'll think about it, but I'll close this issue for now.
