### ISSUE TITLE
RFC: Name of Options.Applicative.BashCompletion module

### ISSUE THREAD

**Issue by hseg** [pcapriotti/optparse-applicative#493]
Given that the module ships completers for multiple shells, not just bash, shouldn't it be called `Options.Applicative.Completion` or something?
I can understand not wanting to change the name due to breakage, but I thought I'd open this for tracking purposes.

**Comment by HuwCampbell** [comment]
Yeah it's a bit of an historical misnomer. I don't think it's worth worrying about to be honest.
