### ISSUE TITLE
Optparse hanging infinitely & support for multiple usage of the same flag

### ISSUE THREAD

**Issue by wdanilo** [pcapriotti/optparse-applicative#58]
Hi!
Would it be possible to add support for multiple usage of the same flag?
I would love to allow users to use arguments like this `myprog --dump ast --dump va --dump test` and I would like to get array of String's as a result.

And here is what I was trying (what was natural to me, because I have some Parsec background) and it hanged optparse when printing help:

`[...] many (strOption (long "dump" <> value "" <> metavar "DUMP")) [...]`

Thank you.

**Comment by danse** [comment]
i stumbled upon this same problem today. i tried a clumsy `option (many str)` and got a scary runtime loop. this seems like a noob trap, i propose to improve the README with this example, i'll put a quick patch together

**Comment by danse** [comment]
actually the best solution would probably be a function like `manyStrOption = many StrOption`, where the haddock can explain that this is a simple alias. to me this seems the more findable way to avoid similar error to new users of the library, and make adoption easier ... i see that you kept the interface very dry and orthogonal though so you probably want to keep it so

**Comment by danse** [comment]
it could be modified as in #295 but it's not very visible, maybe we could have some examples of this usage elsewhere, or point to a guide which goes through applicative parsing?
