### ISSUE TITLE
Possibility to create hidden commands

### ISSUE THREAD

**Issue by wdanilo** [pcapriotti/optparse-applicative#59]
Right now we are able to create hidden options (not displayed in the help), but as far as I know we cannot create hidden commands - would it be possible to add such feature please?

thank you.

**Comment by bos** [comment]
I'd like something like this too.

Concretely, I spell with British English ("analyse"), but I want to be able to support American English users too ("analyze"). So *really* what I want is a way to specify synonyms that identify a single command. But a hidden command would do as a workaround.

**Comment by HuwCampbell** [comment]
One can create a hidden subparser which contains all the aliases, and use alternative to use either the shown commands or the hidden ones.

**Comment by HuwCampbell** [comment]
Also `internal` works with `Mod CommandFields` which will really not show the commands in the subparser (with hidden they will show in full descriptions).

**Comment by HuwCampbell** [comment]
I'm satisfied that this is possible. Closing.

**Comment by edsko** [comment]
Ok, @HuwCampbell 's solution worked for me. Might perhaps be worth mentioning it in the docs for `hidden` or `internal`.
