### ISSUE TITLE
Optional arguments are not supported

### ISSUE THREAD

**Issue by edsko** [pcapriotti/optparse-applicative#67]
Small example:

``` Haskell
{-# LANGUAGE RankNTypes #-}
import Options.Applicative
import Options.Applicative.Builder.Internal

data Options = Options {
    optionsA :: Bool
  , optionsB :: Maybe String
  }
  deriving Show

optionalArg :: (forall f a. HasName f => Mod f a) -> Parser (Maybe String)
optionalArg opts =
 (Just <$> strOption (opts <> value "")) <|> (flag' Nothing opts)

optionsParser :: Parser Options
optionsParser = Options
  <$> switch (long "a")
  <*> optionalArg (long "b")

main :: IO ()
main = execParser opts >>= print
  where
    opts = info (helper <*> optionsParser) fullDesc
```

The help text is correct:

```
Usage: T [--a] ([--b ARG] | [--b])
```

but the parser does not work:

```
# ./T --b
Usage: T [--a] ([--b ARG] | [--b])

# ./T --b --a
Options {optionsA = False, optionsB = Just "--a"}

# ./T --b foo --a
Options {optionsA = True, optionsB = Just "foo"}
```

Only the last one of these three is correct.

**Comment by legrostdg** [comment]
Did you make any progress on this? Wouldn't it be better to keep this (valid) bug opened in the meantime? (I think it's the second time I encountered this and searched in open issues :-))

**Comment by HuwCampbell** [comment]
Please see #194 for my recent take on this.
With regards to reopening, I think no, it's a won't fix, as it could make optparse ambiguous in certain cases.

**Comment by legrostdg** [comment]
OK, it wasn't clear to me that this was a won't fix...

The ambiguity could be avoided if `-` was not allowed at the beginning of the option, couldn't it? Maybe a new `optionWithDefault` explaining this behaviour could be added?
