### ISSUE TITLE
Misleading error reports for two sub-parsers

### ISSUE THREAD

**Issue by amigalemming** [pcapriotti/optparse-applicative#92]
I have a tool that runs in two phases, both phases share some options and have additional custom options. I want to run

~~~~
$ tool --phase1 --max-num=4 --verbose --phase2 --max-num=3 --special
~~~~

Here `max-num=4` and `verbose` belong to phase 1 and `max-num=3` and
`special` belong to phase 2. The order of options within a phase, like `max-num=4` and `verbose`, is irrelevant.

Mr. Capriotti suggested to define two subparsers each with a command. This is what I did. It means that `phase1` and `phase2` don't start with dashes and that they can appear in any order.

See the attached module which is an extension of the example from the Hackage front page of `optparse-applicative`. There the sub-commands are called `add` and `commit`. I hope it is not too confusing.

Now the following problem arises:
~~~~
$ runhaskell example-complex --hello you add myfile
Usage: example-complex add FILE
  Add a file to the repository
~~~~

That is, the `add` command is completely specified and the `commit` command is missing. However the parser suggests that there is something wrong with the `add` command.

**Comment by HuwCampbell** [comment]
#162 
Although the Missing arguments feature will make this better in 0.12, this PR should fix it completely.

**Comment by HuwCampbell** [comment]
Merged, please reopen if there's any issues.
